// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: announcements.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const announcementsMetadata = `-- name: AnnouncementsMetadata :one
select
  count(id) as total_size
from announcements
where
  deleted_at is null
  and "namespace" = $1
`

func (q *Queries) AnnouncementsMetadata(ctx context.Context, namespace string) (int64, error) {
	row := q.db.QueryRowContext(ctx, announcementsMetadata, namespace)
	var total_size int64
	err := row.Scan(&total_size)
	return total_size, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
insert into announcements (
  id,
  "namespace",
  title,
  content,
  style,
  href,
  starts_at,
  ends_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
) returning id
`

type CreateAnnouncementParams struct {
	ID        uuid.UUID
	Namespace string
	Title     string
	Content   string
	Style     string
	Href      sql.NullString
	StartsAt  time.Time
	EndsAt    time.Time
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAnnouncement,
		arg.ID,
		arg.Namespace,
		arg.Title,
		arg.Content,
		arg.Style,
		arg.Href,
		arg.StartsAt,
		arg.EndsAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
update announcements
set deleted_at = now()
where id = $1
  and deleted_at is null
  and "namespace" = $2
`

type DeleteAnnouncementParams struct {
	ID        uuid.UUID
	Namespace string
}

func (q *Queries) DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnnouncement, arg.ID, arg.Namespace)
	return err
}

const findAnnouncementByID = `-- name: FindAnnouncementByID :one
select
  id,
  "namespace",
  title,
  content,
  style,
  href,
  starts_at,
  ends_at,
  created_at,
  updated_at
from announcements
where
  deleted_at is null
  and id = $1
  and "namespace" = $2
`

type FindAnnouncementByIDRow struct {
	ID        uuid.UUID
	Namespace string
	Title     string
	Content   string
	Style     string
	Href      sql.NullString
	StartsAt  time.Time
	EndsAt    time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) FindAnnouncementByID(ctx context.Context, id uuid.UUID, namespace string) (FindAnnouncementByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findAnnouncementByID, id, namespace)
	var i FindAnnouncementByIDRow
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Title,
		&i.Content,
		&i.Style,
		&i.Href,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
select
  id,
  "namespace",
  title,
  content,
  style,
  href,
  starts_at,
  ends_at,
  created_at,
  updated_at
from announcements
where
  deleted_at is null
  and "namespace" = $1
  and starts_at <= now()
  and ends_at > now()
order by starts_at desc
limit 10
`

type ListActiveAnnouncementsRow struct {
	ID        uuid.UUID
	Namespace string
	Title     string
	Content   string
	Style     string
	Href      sql.NullString
	StartsAt  time.Time
	EndsAt    time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListActiveAnnouncements(ctx context.Context, namespace string) ([]ListActiveAnnouncementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAnnouncements, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAnnouncementsRow
	for rows.Next() {
		var i ListActiveAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Title,
			&i.Content,
			&i.Style,
			&i.Href,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
select
  id,
  "namespace",
  title,
  content,
  style,
  href,
  starts_at,
  ends_at,
  created_at,
  updated_at
from announcements
where
  deleted_at is null
  and "namespace" = $1
order by created_at desc
limit $3
offset $2
`

type ListAnnouncementsParams struct {
	Namespace string
	StartFrom int32
	PageSize  int32
}

type ListAnnouncementsRow struct {
	ID        uuid.UUID
	Namespace string
	Title     string
	Content   string
	Style     string
	Href      sql.NullString
	StartsAt  time.Time
	EndsAt    time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]ListAnnouncementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements, arg.Namespace, arg.StartFrom, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnnouncementsRow
	for rows.Next() {
		var i ListAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Title,
			&i.Content,
			&i.Style,
			&i.Href,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
update announcements
set
  "namespace" = $1,
  title = $2,
  content = $3,
  style = $4,
  href = $5,
  starts_at = $6,
  ends_at = $7,
  updated_at = now()
where
  id = $8 and
  deleted_at is null
returning id
`

type UpdateAnnouncementParams struct {
	Namespace string
	Title     string
	Content   string
	Style     string
	Href      sql.NullString
	StartsAt  time.Time
	EndsAt    time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updateAnnouncement,
		arg.Namespace,
		arg.Title,
		arg.Content,
		arg.Style,
		arg.Href,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
