// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: posts.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
insert into posts (
  id,
  "namespace",
  slug,
  current_content_id,
  published_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5
) returning id
`

type CreatePostParams struct {
	ID               uuid.UUID
	Namespace        string
	Slug             string
	CurrentContentID uuid.UUID
	PublishedAt      sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Namespace,
		arg.Slug,
		arg.CurrentContentID,
		arg.PublishedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPostContent = `-- name: CreatePostContent :one
insert into posts_content (
  id,
  post_id,
  title,
  content
) values (
  $1,
  $2,
  $3,
  $4
) returning id
`

type CreatePostContentParams struct {
	ID      uuid.UUID
	PostID  uuid.UUID
	Title   string
	Content string
}

func (q *Queries) CreatePostContent(ctx context.Context, arg CreatePostContentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createPostContent,
		arg.ID,
		arg.PostID,
		arg.Title,
		arg.Content,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePost = `-- name: DeletePost :exec
update posts
set deleted_at = now()
where id = $1
  and deleted_at is null
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const findPostByID = `-- name: FindPostByID :one
select
  posts.id,
  "namespace",
  slug,
  posts_content.title,
  posts_content.content,
  published_at,
  posts.created_at,
  posts.updated_at
from posts
inner join posts_content
  on posts_content.id = posts.current_content_id
where
  deleted_at is null
  and posts.id = $1
`

type FindPostByIDRow struct {
	ID          uuid.UUID
	Namespace   string
	Slug        string
	Title       string
	Content     string
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) FindPostByID(ctx context.Context, id uuid.UUID) (FindPostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findPostByID, id)
	var i FindPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPostBySlug = `-- name: FindPostBySlug :one
select
  posts.id,
  "namespace",
  slug,
  posts_content.title,
  posts_content.content,
  published_at,
  posts.created_at,
  posts.updated_at
from posts
inner join posts_content
  on posts_content.id = posts.current_content_id
where
  deleted_at is null
  and "namespace" = $1
  and slug = $2
`

type FindPostBySlugParams struct {
	Namespace string
	Slug      string
}

type FindPostBySlugRow struct {
	ID          uuid.UUID
	Namespace   string
	Slug        string
	Title       string
	Content     string
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) FindPostBySlug(ctx context.Context, arg FindPostBySlugParams) (FindPostBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, findPostBySlug, arg.Namespace, arg.Slug)
	var i FindPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostVersion = `-- name: GetPostVersion :one
select
  id,
  title,
  content,
  created_at
from posts_content
where id = $1
  and post_id = $2
`

type GetPostVersionParams struct {
	ID     uuid.UUID
	PostID uuid.UUID
}

type GetPostVersionRow struct {
	ID        uuid.UUID
	Title     string
	Content   string
	CreatedAt time.Time
}

func (q *Queries) GetPostVersion(ctx context.Context, arg GetPostVersionParams) (GetPostVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getPostVersion, arg.ID, arg.PostID)
	var i GetPostVersionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listPostVersions = `-- name: ListPostVersions :many
select
  id,
  title,
  created_at
from posts_content
where post_id = $1
order by created_at asc
`

type ListPostVersionsRow struct {
	ID        uuid.UUID
	Title     string
	CreatedAt time.Time
}

func (q *Queries) ListPostVersions(ctx context.Context, postID uuid.UUID) ([]ListPostVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostVersions, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostVersionsRow
	for rows.Next() {
		var i ListPostVersionsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
select
  posts.id,
  "namespace",
  slug,
  posts_content.title,
  posts_content.content,
  published_at,
  posts.created_at,
  posts.updated_at
from posts
inner join posts_content
  on posts_content.id = posts.current_content_id
where
  deleted_at is null
  and ($1::boolean or published_at is not null)
  and "namespace" = $2
order by posts.created_at desc
limit $4
offset $3
`

type ListPostsParams struct {
	IncludeDrafts bool
	Namespace     string
	StartFrom     int32
	PageSize      int32
}

type ListPostsRow struct {
	ID          uuid.UUID
	Namespace   string
	Slug        string
	Title       string
	Content     string
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts,
		arg.IncludeDrafts,
		arg.Namespace,
		arg.StartFrom,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postsMetadata = `-- name: PostsMetadata :one
select
  count(posts.id) as total_size,
  $1::boolean as drafts_included
from posts
where
  deleted_at is null
  and ($1::boolean or published_at is not null)
  and "namespace" = $2
`

type PostsMetadataParams struct {
	IncludeDrafts bool
	Namespace     string
}

type PostsMetadataRow struct {
	TotalSize      int64
	DraftsIncluded bool
}

func (q *Queries) PostsMetadata(ctx context.Context, arg PostsMetadataParams) (PostsMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, postsMetadata, arg.IncludeDrafts, arg.Namespace)
	var i PostsMetadataRow
	err := row.Scan(&i.TotalSize, &i.DraftsIncluded)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
update posts
set
  slug = $1,
  current_content_id = $2,
  published_at = $3,
  updated_at = now()
where
  id = $4 and
  deleted_at is null
returning id
`

type UpdatePostParams struct {
	Slug             string
	CurrentContentID uuid.UUID
	PublishedAt      sql.NullTime
	ID               uuid.UUID
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.Slug,
		arg.CurrentContentID,
		arg.PublishedAt,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updatePostMetadata = `-- name: UpdatePostMetadata :one
update posts
set
  slug = $1,
  published_at = $2,
  updated_at = now()
where
  id = $3 and
  deleted_at is null
returning id
`

type UpdatePostMetadataParams struct {
	Slug        string
	PublishedAt sql.NullTime
	ID          uuid.UUID
}

func (q *Queries) UpdatePostMetadata(ctx context.Context, arg UpdatePostMetadataParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updatePostMetadata, arg.Slug, arg.PublishedAt, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
