load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fliptmanagement",
    srcs = ["client.go"],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/infra/fliptmanagement",
    visibility = ["//services/tadoku-api:infrastructure_consumers"],
    deps = ["@com_github_google_uuid//:uuid"],
)
