apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: tadoku-dev-db
  labels:
    app.kubernetes.io/part-of: tadoku-dev
spec:
  teamId: tadoku
  numberOfInstances: 1
  users:
    immersion: []
    keto: []
    kratos: []
  databases:
    immersion: immersion
    keto: keto
    kratos: kratos
  postgresql:
    version: "17"
  volume:
    size: 2Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
