// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/labstack/echo/v4"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Page defines model for Page.
type Page struct {
	Html        string             `json:"html"`
	Id          openapi_types.UUID `json:"id"`
	PublishedAt *time.Time         `json:"published_at,omitempty"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
}

// CreatePageJSONRequestBody defines body for CreatePage for application/json ContentType.
type CreatePageJSONRequestBody = Page

// UpdatePageJSONRequestBody defines body for UpdatePage for application/json ContentType.
type UpdatePageJSONRequestBody = Page

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creates a new page
	// (POST /pages)
	CreatePage(ctx echo.Context) error
	// Updates an existing page
	// (PUT /pages/{id})
	UpdatePage(ctx echo.Context, id string) error
	// Returns page content for a given slug
	// (GET /pages/{pageSlug})
	FindPageBySlug(ctx echo.Context, pageSlug string) error
	// Checks if service is responsive
	// (GET /ping)
	Ping(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreatePage converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePage(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreatePage(ctx)
	return err
}

// UpdatePage converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatePage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatePage(ctx, id)
	return err
}

// FindPageBySlug converts echo context to params.
func (w *ServerInterfaceWrapper) FindPageBySlug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pageSlug" -------------
	var pageSlug string

	err = runtime.BindStyledParameterWithLocation("simple", false, "pageSlug", runtime.ParamLocationPath, ctx.Param("pageSlug"), &pageSlug)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSlug: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindPageBySlug(ctx, pageSlug)
	return err
}

// Ping converts echo context to params.
func (w *ServerInterfaceWrapper) Ping(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Ping(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/pages", wrapper.CreatePage)
	router.PUT(baseURL+"/pages/:id", wrapper.UpdatePage)
	router.GET(baseURL+"/pages/:pageSlug", wrapper.FindPageBySlug)
	router.GET(baseURL+"/ping", wrapper.Ping)

}
