apiVersion: v1
kind: Namespace
metadata:
  name: tdk-content-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  namespace: tdk-content-api
  labels:
    app: content-api
spec:
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      serviceAccountName: content-api
      initContainers:
        - name: migrations
          image: content-api-migrate-image
          command: ['/migrate']
          args: ['-source', 'file:///migrations', '-database', '$(DATABASE_URL)', 'up']
          env:
          - name: DATABASE_URL
            value: "postgres://content:foobar@postgres-content.default/content?sslmode=disable"
      containers:
      - name: content-api
        image: content-api-image
        ports:
        - containerPort: 8000
        env:
          - name: API_POSTGRES_URL
            value: "postgres://content:foobar@postgres-content.default/content?sslmode=disable"
          - name: API_PORT
            value: "8000"
          - name: API_JWKS
            value: "http://oathkeeper-api.default:4456/.well-known/jwks.json"
          - name: API_KETO_READ_URL
            value: "http://keto-read.default:4466"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: content-api
  namespace: tdk-content-api
  labels:
    app: content-api
    service: content-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: content-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: content-api
  namespace: tdk-content-api
