apiVersion: v1
kind: Namespace
metadata:
  name: tdk-content-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  namespace: tdk-content-api
  labels:
    app: content-api
spec:
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      serviceAccountName: content-api
      initContainers:
        - name: migrations
          image: bazel/services/content-api/storage/postgres/migrations:latest
          imagePullPolicy: IfNotPresent
          command: ['/migrate']
          args: ['-source', 'file:///migrations', '-database', '$(DATABASE_URL)', 'up']
          env:
          - name: DATABASE_URL
            value: "postgres://content:foobar@postgres-content.default/content?sslmode=disable"
      containers:
      - name: content-api
        image: bazel/services/content-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: API_POSTGRES_URL
            value: "postgres://content:foobar@postgres-content.default/content?sslmode=disable"
          - name: API_PORT
            value: "8000"
          - name: API_JWKS
            value: "http://oathkeeper-api.default:4456/.well-known/jwks.json"
        volumeMounts:
        - name: tadoku-permissions
          mountPath: /etc/tadoku/permissions
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
      volumes:
        - name: tadoku-permissions
          configMap:
            name: tadoku-permissions
---
apiVersion: v1
kind: Service
metadata:
  name: content-api
  namespace: tdk-content-api
  labels:
    app: content-api
    service: content-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: content-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: content-api
  namespace: tdk-content-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tadoku-permissions
  namespace: tdk-content-api
data:
  roles.yaml: |
    users:
      - email: dev@tadoku.app
        role: admin
      - email: dev1@tadoku.app
        role: admin
      - email: dev2@tadoku.app
        role: admin
      - email: dev3@tadoku.app
        role: admin
      - email: dev4@tadoku.app
        role: admin
      - email: banned@tadoku.app
        role: banned
