load('ext://helm_remote', 'helm_remote')

helm_remote('kong',
            repo_name='kong',
            repo_url='https://charts.konghq.com',
            version='2.6.4',
            set=['ingressController.installCRDs=false'])

k8s_yaml('./ingress.yaml')
