load('ext://helm_resource', 'helm_resource', 'helm_repo')

k8s_yaml('./ingress.yaml')

helm_repo('kong', 'https://charts.konghq.com', resource_name='helm-repo-kong', labels=["infra"])
helm_resource('kong',
              'kong/kong',
              flags=[
                '--version', '2.6.4',
                '--set', 'ingressController.installCRDs=false'
              ],
              resource_deps=['helm-repo-kong'])

k8s_resource("kong", labels=["infra"])
