// Package internalapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package internalapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/labstack/echo/v4"
)

const (
	ServiceAuthScopes = "serviceAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// InternalPermissionCheckRequest defines model for InternalPermissionCheckRequest.
type InternalPermissionCheckRequest struct {
	Namespace  string      `json:"namespace"`
	Object     string      `json:"object"`
	Relation   string      `json:"relation"`
	SubjectId  *string     `json:"subject_id,omitempty"`
	SubjectSet *SubjectSet `json:"subject_set,omitempty"`
}

// PermissionCheckResponse defines model for PermissionCheckResponse.
type PermissionCheckResponse struct {
	Allowed bool `json:"allowed"`
}

// RelationshipWriteRequest defines model for RelationshipWriteRequest.
type RelationshipWriteRequest struct {
	Namespace  string      `json:"namespace"`
	Object     string      `json:"object"`
	Relation   string      `json:"relation"`
	SubjectId  *string     `json:"subject_id,omitempty"`
	SubjectSet *SubjectSet `json:"subject_set,omitempty"`
}

// SubjectSet defines model for SubjectSet.
type SubjectSet struct {
	Namespace string `json:"namespace"`
	Object    string `json:"object"`
	Relation  string `json:"relation"`
}

// InternalPermissionCheckJSONRequestBody defines body for InternalPermissionCheck for application/json ContentType.
type InternalPermissionCheckJSONRequestBody = InternalPermissionCheckRequest

// InternalRelationshipDeleteJSONRequestBody defines body for InternalRelationshipDelete for application/json ContentType.
type InternalRelationshipDeleteJSONRequestBody = RelationshipWriteRequest

// InternalRelationshipCreateJSONRequestBody defines body for InternalRelationshipCreate for application/json ContentType.
type InternalRelationshipCreateJSONRequestBody = RelationshipWriteRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// InternalPermissionCheck request with any body
	InternalPermissionCheckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InternalPermissionCheck(ctx context.Context, body InternalPermissionCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InternalPing request
	InternalPing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InternalRelationshipDelete request with any body
	InternalRelationshipDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InternalRelationshipDelete(ctx context.Context, body InternalRelationshipDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InternalRelationshipCreate request with any body
	InternalRelationshipCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InternalRelationshipCreate(ctx context.Context, body InternalRelationshipCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) InternalPermissionCheckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalPermissionCheckRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalPermissionCheck(ctx context.Context, body InternalPermissionCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalPermissionCheckRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalPing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalPingRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalRelationshipDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalRelationshipDeleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalRelationshipDelete(ctx context.Context, body InternalRelationshipDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalRelationshipDeleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalRelationshipCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalRelationshipCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalRelationshipCreate(ctx context.Context, body InternalRelationshipCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalRelationshipCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewInternalPermissionCheckRequest calls the generic InternalPermissionCheck builder with application/json body
func NewInternalPermissionCheckRequest(server string, body InternalPermissionCheckJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInternalPermissionCheckRequestWithBody(server, "application/json", bodyReader)
}

// NewInternalPermissionCheckRequestWithBody generates requests for InternalPermissionCheck with any type of body
func NewInternalPermissionCheckRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/permission/check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInternalPingRequest generates requests for InternalPing
func NewInternalPingRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/ping")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewInternalRelationshipDeleteRequest calls the generic InternalRelationshipDelete builder with application/json body
func NewInternalRelationshipDeleteRequest(server string, body InternalRelationshipDeleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInternalRelationshipDeleteRequestWithBody(server, "application/json", bodyReader)
}

// NewInternalRelationshipDeleteRequestWithBody generates requests for InternalRelationshipDelete with any type of body
func NewInternalRelationshipDeleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/relationships")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInternalRelationshipCreateRequest calls the generic InternalRelationshipCreate builder with application/json body
func NewInternalRelationshipCreateRequest(server string, body InternalRelationshipCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInternalRelationshipCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewInternalRelationshipCreateRequestWithBody generates requests for InternalRelationshipCreate with any type of body
func NewInternalRelationshipCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/relationships")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// InternalPermissionCheck request with any body
	InternalPermissionCheckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalPermissionCheckResponse, error)

	InternalPermissionCheckWithResponse(ctx context.Context, body InternalPermissionCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalPermissionCheckResponse, error)

	// InternalPing request
	InternalPingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*InternalPingResponse, error)

	// InternalRelationshipDelete request with any body
	InternalRelationshipDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalRelationshipDeleteResponse, error)

	InternalRelationshipDeleteWithResponse(ctx context.Context, body InternalRelationshipDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalRelationshipDeleteResponse, error)

	// InternalRelationshipCreate request with any body
	InternalRelationshipCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalRelationshipCreateResponse, error)

	InternalRelationshipCreateWithResponse(ctx context.Context, body InternalRelationshipCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalRelationshipCreateResponse, error)
}

type InternalPermissionCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PermissionCheckResponse
}

// Status returns HTTPResponse.Status
func (r InternalPermissionCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InternalPermissionCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InternalPingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r InternalPingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InternalPingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InternalRelationshipDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r InternalRelationshipDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InternalRelationshipDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InternalRelationshipCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r InternalRelationshipCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InternalRelationshipCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// InternalPermissionCheckWithBodyWithResponse request with arbitrary body returning *InternalPermissionCheckResponse
func (c *ClientWithResponses) InternalPermissionCheckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalPermissionCheckResponse, error) {
	rsp, err := c.InternalPermissionCheckWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalPermissionCheckResponse(rsp)
}

func (c *ClientWithResponses) InternalPermissionCheckWithResponse(ctx context.Context, body InternalPermissionCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalPermissionCheckResponse, error) {
	rsp, err := c.InternalPermissionCheck(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalPermissionCheckResponse(rsp)
}

// InternalPingWithResponse request returning *InternalPingResponse
func (c *ClientWithResponses) InternalPingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*InternalPingResponse, error) {
	rsp, err := c.InternalPing(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalPingResponse(rsp)
}

// InternalRelationshipDeleteWithBodyWithResponse request with arbitrary body returning *InternalRelationshipDeleteResponse
func (c *ClientWithResponses) InternalRelationshipDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalRelationshipDeleteResponse, error) {
	rsp, err := c.InternalRelationshipDeleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalRelationshipDeleteResponse(rsp)
}

func (c *ClientWithResponses) InternalRelationshipDeleteWithResponse(ctx context.Context, body InternalRelationshipDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalRelationshipDeleteResponse, error) {
	rsp, err := c.InternalRelationshipDelete(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalRelationshipDeleteResponse(rsp)
}

// InternalRelationshipCreateWithBodyWithResponse request with arbitrary body returning *InternalRelationshipCreateResponse
func (c *ClientWithResponses) InternalRelationshipCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalRelationshipCreateResponse, error) {
	rsp, err := c.InternalRelationshipCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalRelationshipCreateResponse(rsp)
}

func (c *ClientWithResponses) InternalRelationshipCreateWithResponse(ctx context.Context, body InternalRelationshipCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalRelationshipCreateResponse, error) {
	rsp, err := c.InternalRelationshipCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalRelationshipCreateResponse(rsp)
}

// ParseInternalPermissionCheckResponse parses an HTTP response from a InternalPermissionCheckWithResponse call
func ParseInternalPermissionCheckResponse(rsp *http.Response) (*InternalPermissionCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InternalPermissionCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PermissionCheckResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseInternalPingResponse parses an HTTP response from a InternalPingWithResponse call
func ParseInternalPingResponse(rsp *http.Response) (*InternalPingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InternalPingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseInternalRelationshipDeleteResponse parses an HTTP response from a InternalRelationshipDeleteWithResponse call
func ParseInternalRelationshipDeleteResponse(rsp *http.Response) (*InternalRelationshipDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InternalRelationshipDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseInternalRelationshipCreateResponse parses an HTTP response from a InternalRelationshipCreateWithResponse call
func ParseInternalRelationshipCreateResponse(rsp *http.Response) (*InternalRelationshipCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InternalRelationshipCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Checks a permission for an arbitrary subject (no allowlist)
	// (POST /internal/v1/permission/check)
	InternalPermissionCheck(ctx echo.Context) error
	// Internal health check for service-to-service calls
	// (GET /internal/v1/ping)
	InternalPing(ctx echo.Context) error
	// Deletes a relation tuple in Keto (allowlisted per-service)
	// (DELETE /internal/v1/relationships)
	InternalRelationshipDelete(ctx echo.Context) error
	// Creates a relation tuple in Keto (allowlisted per-service)
	// (POST /internal/v1/relationships)
	InternalRelationshipCreate(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// InternalPermissionCheck converts echo context to params.
func (w *ServerInterfaceWrapper) InternalPermissionCheck(ctx echo.Context) error {
	var err error

	ctx.Set(ServiceAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalPermissionCheck(ctx)
	return err
}

// InternalPing converts echo context to params.
func (w *ServerInterfaceWrapper) InternalPing(ctx echo.Context) error {
	var err error

	ctx.Set(ServiceAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalPing(ctx)
	return err
}

// InternalRelationshipDelete converts echo context to params.
func (w *ServerInterfaceWrapper) InternalRelationshipDelete(ctx echo.Context) error {
	var err error

	ctx.Set(ServiceAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalRelationshipDelete(ctx)
	return err
}

// InternalRelationshipCreate converts echo context to params.
func (w *ServerInterfaceWrapper) InternalRelationshipCreate(ctx echo.Context) error {
	var err error

	ctx.Set(ServiceAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalRelationshipCreate(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/internal/v1/permission/check", wrapper.InternalPermissionCheck)
	router.GET(baseURL+"/internal/v1/ping", wrapper.InternalPing)
	router.DELETE(baseURL+"/internal/v1/relationships", wrapper.InternalRelationshipDelete)
	router.POST(baseURL+"/internal/v1/relationships", wrapper.InternalRelationshipCreate)

}
