load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("//.dev:frontend.bzl", "frontend_dev")

pkg_tar(
    name = "pnpm_dev_layer",
    symlinks = {"/usr/local/bin/pnpm": "/opt/pnpm/bin/pnpm.cjs"},
    deps = ["@tadoku_dev_pnpm//:layer"],
)

frontend_dev(
    name = "webv2",
    host = "tadoku.dev.lab",
)

frontend_dev(
    name = "auth",
    host = "account.tadoku.dev.lab",
    readiness_path = "/login",
)

frontend_dev(
    name = "admin",
    host = "admin.tadoku.dev.lab",
)
