FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm@10.10.0 && pnpm config set store-dir .pnpm-store
COPY pnpm-lock.yaml .npmrc* ./
RUN pnpm fetch

COPY . .
RUN pnpm install -r --offline

EXPOSE 3000