k8s_yaml('./auth/deployments/frontend-auth.yaml')

k8s_resource("frontend-auth", port_forwards="3001", labels=["frontend"])

docker_build(
  'frontend-auth', 
  context='.',
  dockerfile = './auth/Dockerfile.dev',
  live_update=[
    sync('./', '/app'),
    run('cd /app/auth && yarn install', trigger=['./auth/package.json', './auth/yarn.lock']),
  ]
)