load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "leaderboard",
    srcs = [
        "domain.go",
        "leaderboard_repository.go",
        "leaderboard_service.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/features/leaderboard",
    visibility = ["//visibility:public"],
    deps = [
        "//services/tadoku-api/domain/activities",
        "//services/tadoku-api/generated/sqlc/leaderboard",
        "//services/tadoku-api/infra/postgres",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/timex",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgx_v5//pgtype",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@com_github_valkey_io_valkey_go//:valkey-go",
    ],
)
