load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "s2s",
    srcs = [
        "client.go",
        "transport.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/common/client/s2s",
    visibility = ["//visibility:public"],
)

go_test(
    name = "s2s_test",
    srcs = ["transport_test.go"],
    embed = [":s2s"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
