load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "featureaccess",
    srcs = [
        "domain.go",
        "featureaccess_service.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/features/featureaccess",
    visibility = ["//visibility:public"],
    deps = [
        "//services/common/featureflags",
        "//services/tadoku-api/infra/fliptmanagement",
        "//services/tadoku-api/internal/errx",
        "@com_github_google_uuid//:uuid",
    ],
)
