load("@rules_go//go:def.bzl", "go_library", "go_test")

go_test(
    name = "posts_test",
    srcs = [
        "posts_repository_test.go",
        "posts_service_test.go",
    ],
    args = ["-test.parallel=4"],
    env_inherit = ["TADOKU_TEST_POSTGRES_URL"],
    tags = [
        "no-cache",
        "no-remote-exec",
        "requires-network",
    ],
    deps = [
        ":posts",
        "//services/tadoku-api/infra/postgres",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/testpostgres",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgerrcode//:pgerrcode",
        "@com_github_jackc_pgx_v5//pgconn",
    ],
)

go_library(
    name = "posts",
    srcs = [
        "domain.go",
        "posts_repository.go",
        "posts_service.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/features/posts",
    visibility = ["//services/tadoku-api:feature_consumers"],
    deps = [
        "//services/tadoku-api/generated/sqlc/posts",
        "//services/tadoku-api/infra/postgres",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/timex",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgtype",
        "@com_github_jackc_pgx_v5//pgxpool",
    ],
)
