load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_binary(
    name = "copy-database",
    srcs = ["copy-database.sh"],
    visibility = ["//visibility:public"],
)

sh_test(
    name = "copy-database_test",
    srcs = ["copy-database_test.sh"],
    args = ["$(rlocationpath :copy-database)"],
    data = [":copy-database"],
)
