// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/labstack/echo/v4"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Page defines model for Page.
type Page struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Html        *string             `json:"html,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	PublishedAt *time.Time          `json:"published_at,omitempty"`
	Slug        string              `json:"slug"`
	Title       string              `json:"title"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// PageVersion defines model for PageVersion.
type PageVersion struct {
	CreatedAt time.Time `json:"created_at"`
	Html      *string   `json:"html,omitempty"`

	// Id Content ID of this version
	Id    openapi_types.UUID `json:"id"`
	Title string             `json:"title"`

	// Version Version number (starting at 1)
	Version int `json:"version"`
}

// PageVersions defines model for PageVersions.
type PageVersions struct {
	Versions []PageVersion `json:"versions"`
}

// Pages defines model for Pages.
type Pages struct {
	// NextPageToken is empty if there's no next page
	NextPageToken string `json:"next_page_token"`
	Pages         []Page `json:"pages"`
	TotalSize     int    `json:"total_size"`
}

// PaginatedList defines model for PaginatedList.
type PaginatedList struct {
	// NextPageToken is empty if there's no next page
	NextPageToken string `json:"next_page_token"`
	TotalSize     int    `json:"total_size"`
}

// Post defines model for Post.
type Post struct {
	Content     string              `json:"content"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Namespace   *string             `json:"namespace,omitempty"`
	PublishedAt *time.Time          `json:"published_at,omitempty"`
	Slug        string              `json:"slug"`
	Title       string              `json:"title"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// PostVersion defines model for PostVersion.
type PostVersion struct {
	Content   *string   `json:"content,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// Id Content ID of this version
	Id    openapi_types.UUID `json:"id"`
	Title string             `json:"title"`

	// Version Version number (starting at 1)
	Version int `json:"version"`
}

// PostVersions defines model for PostVersions.
type PostVersions struct {
	Versions []PostVersion `json:"versions"`
}

// Posts defines model for Posts.
type Posts struct {
	// NextPageToken is empty if there's no next page
	NextPageToken string `json:"next_page_token"`
	Posts         []Post `json:"posts"`
	TotalSize     int    `json:"total_size"`
}

// PageListParams defines parameters for PageList.
type PageListParams struct {
	PageSize      *int  `form:"page_size,omitempty" json:"page_size,omitempty"`
	Page          *int  `form:"page,omitempty" json:"page,omitempty"`
	IncludeDrafts *bool `form:"include_drafts,omitempty" json:"include_drafts,omitempty"`
}

// PostListParams defines parameters for PostList.
type PostListParams struct {
	PageSize      *int  `form:"page_size,omitempty" json:"page_size,omitempty"`
	Page          *int  `form:"page,omitempty" json:"page,omitempty"`
	IncludeDrafts *bool `form:"include_drafts,omitempty" json:"include_drafts,omitempty"`
}

// PageCreateJSONRequestBody defines body for PageCreate for application/json ContentType.
type PageCreateJSONRequestBody = Page

// PageUpdateJSONRequestBody defines body for PageUpdate for application/json ContentType.
type PageUpdateJSONRequestBody = Page

// PostCreateJSONRequestBody defines body for PostCreate for application/json ContentType.
type PostCreateJSONRequestBody = Post

// PostUpdateJSONRequestBody defines body for PostUpdate for application/json ContentType.
type PostUpdateJSONRequestBody = Post

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// lists all pages
	// (GET /pages/{namespace})
	PageList(ctx echo.Context, namespace string, params PageListParams) error
	// Creates a new page
	// (POST /pages/{namespace})
	PageCreate(ctx echo.Context, namespace string) error
	// Deletes an existing page
	// (DELETE /pages/{namespace}/{id})
	PageDelete(ctx echo.Context, namespace string, id string) error
	// Updates an existing page
	// (PUT /pages/{namespace}/{id})
	PageUpdate(ctx echo.Context, namespace string, id string) error
	// Lists all versions of a page
	// (GET /pages/{namespace}/{id}/versions)
	PageVersionList(ctx echo.Context, namespace string, id string) error
	// Gets a specific version of a page
	// (GET /pages/{namespace}/{id}/versions/{contentId})
	PageVersionGet(ctx echo.Context, namespace string, id string, contentId openapi_types.UUID) error
	// Returns page content for a given slug
	// (GET /pages/{namespace}/{slug})
	PageFindBySlug(ctx echo.Context, namespace string, slug string) error
	// Checks if service is responsive
	// (GET /ping)
	Ping(ctx echo.Context) error
	// lists all posts
	// (GET /posts/{namespace})
	PostList(ctx echo.Context, namespace string, params PostListParams) error
	// Creates a new post
	// (POST /posts/{namespace})
	PostCreate(ctx echo.Context, namespace string) error
	// Deletes an existing post
	// (DELETE /posts/{namespace}/{id})
	PostDelete(ctx echo.Context, namespace string, id string) error
	// Updates an existing post
	// (PUT /posts/{namespace}/{id})
	PostUpdate(ctx echo.Context, namespace string, id string) error
	// Lists all versions of a post
	// (GET /posts/{namespace}/{id}/versions)
	PostVersionList(ctx echo.Context, namespace string, id string) error
	// Gets a specific version of a post
	// (GET /posts/{namespace}/{id}/versions/{contentId})
	PostVersionGet(ctx echo.Context, namespace string, id string, contentId openapi_types.UUID) error
	// Returns page content for a given slug
	// (GET /posts/{namespace}/{slug})
	PostFindBySlug(ctx echo.Context, namespace string, slug string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PageList converts echo context to params.
func (w *ServerInterfaceWrapper) PageList(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PageListParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "include_drafts" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_drafts", ctx.QueryParams(), &params.IncludeDrafts)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter include_drafts: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PageList(ctx, namespace, params)
	return err
}

// PageCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PageCreate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PageCreate(ctx, namespace)
	return err
}

// PageDelete converts echo context to params.
func (w *ServerInterfaceWrapper) PageDelete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PageDelete(ctx, namespace, id)
	return err
}

// PageUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) PageUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PageUpdate(ctx, namespace, id)
	return err
}

// PageVersionList converts echo context to params.
func (w *ServerInterfaceWrapper) PageVersionList(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PageVersionList(ctx, namespace, id)
	return err
}

// PageVersionGet converts echo context to params.
func (w *ServerInterfaceWrapper) PageVersionGet(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "contentId" -------------
	var contentId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "contentId", runtime.ParamLocationPath, ctx.Param("contentId"), &contentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter contentId: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PageVersionGet(ctx, namespace, id, contentId)
	return err
}

// PageFindBySlug converts echo context to params.
func (w *ServerInterfaceWrapper) PageFindBySlug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithLocation("simple", false, "slug", runtime.ParamLocationPath, ctx.Param("slug"), &slug)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PageFindBySlug(ctx, namespace, slug)
	return err
}

// Ping converts echo context to params.
func (w *ServerInterfaceWrapper) Ping(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Ping(ctx)
	return err
}

// PostList converts echo context to params.
func (w *ServerInterfaceWrapper) PostList(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostListParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "include_drafts" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_drafts", ctx.QueryParams(), &params.IncludeDrafts)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter include_drafts: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostList(ctx, namespace, params)
	return err
}

// PostCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostCreate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostCreate(ctx, namespace)
	return err
}

// PostDelete converts echo context to params.
func (w *ServerInterfaceWrapper) PostDelete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostDelete(ctx, namespace, id)
	return err
}

// PostUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) PostUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUpdate(ctx, namespace, id)
	return err
}

// PostVersionList converts echo context to params.
func (w *ServerInterfaceWrapper) PostVersionList(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostVersionList(ctx, namespace, id)
	return err
}

// PostVersionGet converts echo context to params.
func (w *ServerInterfaceWrapper) PostVersionGet(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "contentId" -------------
	var contentId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "contentId", runtime.ParamLocationPath, ctx.Param("contentId"), &contentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter contentId: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostVersionGet(ctx, namespace, id, contentId)
	return err
}

// PostFindBySlug converts echo context to params.
func (w *ServerInterfaceWrapper) PostFindBySlug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithLocation("simple", false, "namespace", runtime.ParamLocationPath, ctx.Param("namespace"), &namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithLocation("simple", false, "slug", runtime.ParamLocationPath, ctx.Param("slug"), &slug)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostFindBySlug(ctx, namespace, slug)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/pages/:namespace", wrapper.PageList)
	router.POST(baseURL+"/pages/:namespace", wrapper.PageCreate)
	router.DELETE(baseURL+"/pages/:namespace/:id", wrapper.PageDelete)
	router.PUT(baseURL+"/pages/:namespace/:id", wrapper.PageUpdate)
	router.GET(baseURL+"/pages/:namespace/:id/versions", wrapper.PageVersionList)
	router.GET(baseURL+"/pages/:namespace/:id/versions/:contentId", wrapper.PageVersionGet)
	router.GET(baseURL+"/pages/:namespace/:slug", wrapper.PageFindBySlug)
	router.GET(baseURL+"/ping", wrapper.Ping)
	router.GET(baseURL+"/posts/:namespace", wrapper.PostList)
	router.POST(baseURL+"/posts/:namespace", wrapper.PostCreate)
	router.DELETE(baseURL+"/posts/:namespace/:id", wrapper.PostDelete)
	router.PUT(baseURL+"/posts/:namespace/:id", wrapper.PostUpdate)
	router.GET(baseURL+"/posts/:namespace/:id/versions", wrapper.PostVersionList)
	router.GET(baseURL+"/posts/:namespace/:id/versions/:contentId", wrapper.PostVersionGet)
	router.GET(baseURL+"/posts/:namespace/:slug", wrapper.PostFindBySlug)

}
