load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "permissions",
    srcs = ["checker.go"],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/internal/permissions",
    visibility = ["//services/tadoku-api:internal_consumers"],
    deps = [
        "//services/common/client/keto",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/identity",
    ],
)

go_test(
    name = "permissions_test",
    size = "medium",
    srcs = ["checker_test.go"],
    embed = [":permissions"],
    tags = [
        "no-cache",
        "no-remote-exec",
        "requires-network",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    deps = [
        "//services/common/client/keto",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/identity",
        "//services/tadoku-api/internal/testketo",
    ],
)
