# Api container
watch_file('./deployments/api.yaml')
k8s_yaml(local('bazel run //services/identity-api/deployments:api'))

custom_build(
  ref='identity-api-image',
  command=(
    'bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 {image_target} -- --norun && ' +
    'docker tag {bazel_image} $EXPECTED_REF').format(
      image_target='//services/identity-api/cmd/server:base_image',
      bazel_image='bazel/services/identity-api/cmd/server:base_image'
    ),
  deps=['./'],
)

k8s_resource('identity-api', port_forwards=8002)

k8s_yaml('./deployments/nats.yaml')
