# Api container
watch_file('./deployments/api.yaml')
k8s_yaml(local('bazel run //services/blog-api/deployments:api'))

custom_build(
  ref='blog-api-migrate-image',
  command=(
    'bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 {image_target} -- --norun && ' +
    'docker tag {bazel_image} $EXPECTED_REF').format(
      image_target='//services/blog-api/storage/postgres/migrations:image',
      bazel_image='bazel/services/blog-api/storage/postgres/migrations:image'
    ),
  deps=['./storage/postgres/migrations/'],
)

custom_build(
  ref='blog-api-image',
  command=(
    'bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 {image_target} -- --norun && ' +
    'docker tag {bazel_image} $EXPECTED_REF').format(
      image_target='//services/blog-api:image',
      bazel_image='bazel/services/blog-api:image'
    ),
  deps=['./'],
)

k8s_resource('blog-api', labels=["backend"])
