DROP TABLE contests CASCADE;
DROP TABLE mediums CASCADE;
DROP TABLE languages CASCADE;
DROP TABLE logs CASCADE;

DROP SEQUENCE IF EXISTS contest_seq;
DROP SEQUENCE IF EXISTS medium_seq;
DROP SEQUENCE IF EXISTS log_seq;
