- id: "tadoku:content:api"
  upstream:
    preserve_host: true
    url: "http://content-api.tdk-content-api:80"
    strip_path: /api/internal/content/
  match:
    url: "http://langlog.be/api/internal/content/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "tadoku:immersion:api"
  upstream:
    preserve_host: true
    url: "http://immersion-api.tdk-immersion-api:80"
    strip_path: /api/internal/immersion/
  match:
    url: "http://langlog.be/api/internal/immersion/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "tadoku:authz:api"
  upstream:
    preserve_host: true
    url: "http://authz-api.tdk-authz-api:80"
    strip_path: /api/internal/authz/
  match:
    url: "http://langlog.be/api/internal/authz/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "tadoku:memory:api"
  upstream:
    preserve_host: true
    url: "http://memory-api:80"
    strip_path: /api/internal/memory/
  match:
    url: "http://langlog.be/api/internal/memory/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "echo"
  upstream:
    preserve_host: true
    url: "http://echo"
    strip_path: /api/internal/echo
  match:
    url: "http://langlog.be/api/internal/echo/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "s2s:immersion-to-profile"
  match:
    url: "http://oathkeeper-proxy.default:4455/token-exchange/profile-api"
    methods:
      - GET
  authenticators:
    - handler: jwt
      config:
        jwks_urls:
          - http://token-reflector.tdk-token-reflector/jwks
        target_audience:
          - oathkeeper
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
      config:
        claims: |
          {
            "type": "service",
            "sub": "{{ .Subject }}",
            "aud": ["profile-api"]
          }
  upstream:
    url: "http://token-reflector.tdk-token-reflector"

- id: "s2s:to-authz"
  match:
    url: "http://oathkeeper-proxy.default:4455/token-exchange/authz-api"
    methods:
      - GET
  authenticators:
    - handler: jwt
      config:
        jwks_urls:
          - http://token-reflector.tdk-token-reflector/jwks
        target_audience:
          - oathkeeper
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
      config:
        claims: |
          {
            "type": "service",
            "sub": "{{ .Subject }}",
            "aud": ["authz-api"]
          }
  upstream:
    url: "http://token-reflector.tdk-token-reflector"
