apiVersion: v1
kind: Secret
metadata:
  name: dev-oathkeeper-authz
  namespace: default
type: Opaque
stringData:
  token: "{{TADOKU_OATHKEEPER_AUTHZ_TOKEN}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-oathkeeper-authz
  namespace: tdk-authz-api
type: Opaque
stringData:
  token: "{{TADOKU_OATHKEEPER_AUTHZ_TOKEN}}"
