load('ext://helm_remote', 'helm_remote')

helm_remote('kratos',
            repo_name='ory',
            repo_url='https://k8s.ory.sh/helm/charts',
            values='./kratos_values.yaml')

k8s_resource("kratos", labels=["auth"])
k8s_resource("kratos-courier", labels=["auth"])
k8s_resource("kratos-automigrate", labels=["auth"])