apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-webv2
  labels:
    app: frontend-webv2
spec:
  selector:
    matchLabels:
      app: frontend-webv2
  template:
    metadata:
      labels:
        app: frontend-webv2
        tier: web
    spec:
      serviceAccountName: frontend-webv2
      automountServiceAccountToken: false
      containers:
      - name: frontend-webv2
        image: frontend-webv2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_KRATOS_INTERNAL_ENDPOINT
          value: http://kratos-public
        - name: NEXT_PUBLIC_KRATOS_ENDPOINT
          value: {{TADOKU_AUTH_URL}}/kratos
        - name: NEXT_PUBLIC_AUTH_UI_URL
          value: {{TADOKU_AUTH_URL}}
        - name: NEXT_PUBLIC_HOME_URL
          value: {{TADOKU_APP_URL}}
        - name: NEXT_PUBLIC_API_ENDPOINT
          value: {{TADOKU_APP_URL}}/api/internal
        - name: NEXT_PUBLIC_COOKIE_DOMAIN
          value: .{{TADOKU_COOKIE_DOMAIN}}
        - name: NEXT_PUBLIC_COOKIE_SECURE
          value: "{{TADOKU_COOKIE_SECURE}}"
        - name: NEXT_PUBLIC_ADMIN_URL
          value: {{TADOKU_ADMIN_URL}}
        - name: WATCHPACK_POLLING
          value: "true"
        - name: WATCHPACK_POLLING_INTERVAL
          value: "1000"
        - name: CHOKIDAR_USEPOLLING
          value: "true"
        - name: OATHKEEPER_URL
          value: http://oathkeeper-proxy.default:4455
        - name: FLIPT_URL
          value: http://oathkeeper-proxy.default:4455/flipt
        - name: FLIPT_ENVIRONMENT
          value: local
        - name: FLIPT_NAMESPACE
          value: default
        - name: FLIPT_UPDATE_INTERVAL
          value: "30"
        - name: FLIPT_STARTUP_TIMEOUT
          value: "3000"
        volumeMounts:
        - name: k8s-token
          mountPath: /var/run/secrets/tokens
          readOnly: true
      volumes:
      - name: k8s-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
              audience: frontend-webv2
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-webv2
  labels:
    app: frontend-webv2
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-webv2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-webv2
automountServiceAccountToken: false
