apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-webv2
  labels:
    app: frontend-webv2
spec:
  selector:
    matchLabels:
      app: frontend-webv2
  template:
    metadata:
      labels:
        app: frontend-webv2
        tier: web
    spec:
      containers:
      - name: frontend-webv2
        image: frontend-webv2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name:  NEXT_PUBLIC_KRATOS_INTERNAL_ENDPOINT
          value: http://kratos-public
        - name: NEXT_PUBLIC_KRATOS_ENDPOINT
          value: {{TADOKU_AUTH_URL}}/kratos
        - name: NEXT_PUBLIC_AUTH_UI_URL
          value: {{TADOKU_AUTH_URL}}
        - name: NEXT_PUBLIC_HOME_URL
          value: {{TADOKU_APP_URL}}
        - name: NEXT_PUBLIC_API_ENDPOINT
          value: {{TADOKU_APP_URL}}/api/internal
        - name: NEXT_PUBLIC_COOKIE_DOMAIN
          value: .{{TADOKU_COOKIE_DOMAIN}}
        - name: NEXT_PUBLIC_ADMIN_URL
          value: {{TADOKU_ADMIN_URL}}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-webv2
  labels:
    app: frontend-webv2
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-webv2
