// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: pages.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findPageBySlug = `-- name: findPageBySlug :one
select
  pages.id,
  slug,
  pages_content.title,
  pages_content.html,
  published_at
from pages
inner join pages_content
  on pages_content.id = pages.current_content_id
where
  deleted_at is null
  and slug = $1
`

type findPageBySlugRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	Html        string
	PublishedAt sql.NullTime
}

func (q *Queries) findPageBySlug(ctx context.Context, slug string) (findPageBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, findPageBySlug, slug)
	var i findPageBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Html,
		&i.PublishedAt,
	)
	return i, err
}
