import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes, useParams } from 'react-router-dom'
import { ToastProvider } from 'paper-ui'
import { beforeEach, expect, it } from 'vitest'
import { initialContests, initialLogs, type SampleLog } from '../src/data'
import { LogEditorPage } from '../src/SupportingPages'
import { PlaygroundProvider, usePlayground } from '../src/state'

function Saved(){const {logId}=useParams();const {logs}=usePlayground();return <output aria-label="Saved record">{JSON.stringify(logs.find(log=>log.id===logId))}</output>}
function show(path:string){return render(<MemoryRouter initialEntries={[path]}><PlaygroundProvider><ToastProvider><Routes><Route path="/logs/new" element={<LogEditorPage/>}/><Route path="/logs/:logId/edit" element={<LogEditorPage/>}/><Route path="/logs/:logId" element={<Saved/>}/></Routes></ToastProvider></PlaygroundProvider></MemoryRouter>)}
async function next(){fireEvent.click(screen.getByRole('button',{name:'Next'}));await screen.findByRole('button',{name:/^Save (activity|changes)$/})}
function openMetadata(){const summary=screen.getByText(/^Metadata/);if(!summary.closest('details')?.open)fireEvent.click(summary)}
beforeEach(()=>{localStorage.clear();localStorage.setItem('tadoku-paper-playground-v1',JSON.stringify({viewer:'participant',logs:initialLogs,contests:initialContests,joinedContests:['round5','reading-circle']}))})
it('validates a positive amount before saving a new personal entry',async()=>{
  show('/logs/new')
  fireEvent.change(screen.getByLabelText('Pages read',{exact:false}),{target:{value:'0'}})
  fireEvent.click(screen.getByRole('button',{name:'Next'}))
  expect(await screen.findByRole('alert')).toHaveTextContent('Enter an amount greater than zero')
  expect(screen.queryByLabelText('Saved record')).not.toBeInTheDocument()
  fireEvent.change(screen.getByLabelText('Pages read',{exact:false}),{target:{value:'12'}})
  fireEvent.change(screen.getByLabelText('What did you read or listen to?'),{target:{value:'A quiet chapter'}})
  await next()
  fireEvent.click(screen.getByRole('button',{name:'Save activity'}))
  const saved=JSON.parse((await screen.findByLabelText('Saved record')).textContent||'{}')
  expect(saved).toMatchObject({title:'A quiet chapter',amount:12,language:'Japanese',activity:'Reading',submissions:[]})
})
it('updates active contest scores with their own rule when editing',async()=>{
  show('/logs/reading-konbini/edit')
  fireEvent.change(screen.getByLabelText('Pages read',{exact:false}),{target:{value:'48'}})
  openMetadata()
  fireEvent.change(screen.getByLabelText('Time spent reading'),{target:{value:'50'}})
  await next()
  fireEvent.click(screen.getByRole('button',{name:'Save changes'}))
  const saved=JSON.parse((await screen.findByLabelText('Saved record')).textContent||'{}')
  expect(saved.submissions).toEqual(expect.arrayContaining([expect.objectContaining({contestId:'round5',score:48}),expect.objectContaining({contestId:'reading-circle',score:25})]))
})
it('keeps closed contribution snapshots while editing the personal record',async()=>{
  show('/logs/ended-reading/edit')
  fireEvent.change(screen.getByLabelText('Pages read',{exact:false}),{target:{value:'60'}})
  await next()
  fireEvent.click(screen.getByRole('button',{name:'Save changes'}))
  await waitFor(()=>expect(screen.getByLabelText('Saved record')).toBeInTheDocument())
  const saved=JSON.parse(screen.getByLabelText('Saved record').textContent||'{}')
  expect(saved.amount).toBe(60)
  expect(saved.submissions.map((s:{score:number})=>s.score)).toEqual([42,22.5])
})

it.each(['reading-konbini','listening-teppei'])('keeps the existing language and activity fixed while saving %s',async id=>{
  const existing=initialLogs.find(log=>log.id===id)!
  show(`/logs/${id}/edit`)
  expect(screen.getByRole('combobox',{name:'Activity'})).toBeDisabled()
  expect(screen.getByRole('combobox',{name:'Activity'})).toHaveValue(existing.activity)
  expect(screen.getByRole('combobox',{name:/Language/})).toBeDisabled()
  expect(screen.getByRole('combobox',{name:/Language/})).toHaveValue(existing.language)
  expect(screen.queryByText('Use a recent log')).not.toBeInTheDocument()
  openMetadata()
  fireEvent.change(screen.getByLabelText('Notes'),{target:{value:'An updated note'}})
  await next()
  fireEvent.click(screen.getByRole('button',{name:'Save changes'}))
  const saved=JSON.parse((await screen.findByLabelText('Saved record')).textContent||'{}')
  expect(saved).toMatchObject({language:existing.language,activity:existing.activity,unit:existing.unit,note:'An updated note'})
})

it('allows a later activity to be edited when reopened without its scenario date',async()=>{
  const october={...initialLogs[0],id:'october-reading',date:'2026-10-01',submissions:[]}
  localStorage.setItem('tadoku-paper-playground-v1',JSON.stringify({viewer:'participant',logs:[...initialLogs,october],contests:initialContests,joinedContests:['round5']}))
  show('/logs/october-reading/edit')
  fireEvent.change(screen.getByLabelText(/Pages read/),{target:{value:'50'}})
  await next()
  expect(screen.getByLabelText(/Activity date/)).toHaveAttribute('max','2026-10-01')
  fireEvent.click(screen.getByRole('button',{name:'Save changes'}))
  const saved=JSON.parse((await screen.findByLabelText('Saved record')).textContent||'{}')
  expect(saved).toMatchObject({date:'2026-10-01',amount:50})
})

it('retains explicit later date context and finished scores when editing an older activity',async()=>{
  show('/logs/reading-konbini/edit?asOf=2026-10-05')
  fireEvent.change(screen.getByLabelText(/Pages read/),{target:{value:'50'}})
  await next()
  expect(screen.getByLabelText(/Activity date/)).toHaveAttribute('max','2026-10-05')
  fireEvent.click(screen.getByRole('button',{name:'Save changes'}))
  const saved=JSON.parse((await screen.findByLabelText('Saved record')).textContent||'{}')
  expect(saved).toMatchObject({date:'2026-09-05',amount:50})
  expect(saved.submissions.map((submission:{score:number})=>submission.score)).toEqual([42,22.5])
})


it('keeps the entered draft when moving back from contest selection', async () => {
  show('/logs/new')
  fireEvent.click(screen.getByRole('button', { name: 'Next' }))
  expect(await screen.findByRole('alert')).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Save activity' })).not.toBeInTheDocument()
  fireEvent.change(screen.getByLabelText(/Pages read/), { target: { value: '20' } })
  fireEvent.change(screen.getByLabelText('What did you read or listen to?'), { target: { value: 'My draft' } })
  await next()
  fireEvent.change(screen.getByLabelText(/Activity date/), { target: { value: '2026-09-03' } })
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  expect(screen.getByLabelText(/Pages read/)).toHaveValue(20)
  expect(screen.getByLabelText('What did you read or listen to?')).toHaveValue('My draft')
  await next()
  expect(screen.getByLabelText(/Activity date/)).toHaveValue('2026-09-03')
  fireEvent.change(screen.getByLabelText(/Activity date/), { target: { value: '' } })
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  await next()
  fireEvent.click(screen.getByRole('button', { name: 'Save activity' }))
  expect(await screen.findByRole('alert')).toBeVisible()
  expect(screen.getByLabelText(/Activity date/)).toBeVisible()
  expect(screen.queryByLabelText('Saved record')).not.toBeInTheDocument()
})

it('shows only your newest entries and appends five older ones without replacing existing rows', () => {
  const logs = Array.from({ length: 11 }, (_, index) => ({ ...initialLogs[0], id: `recent-${index}`, title: `Recent entry ${index}`, date: `2026-08-${String(index + 1).padStart(2, '0')}` }))
  logs.push({ ...logs[0], id: 'someone-else', title: 'Someone else’s entry', userId: 'mei', date: '2026-09-05' })
  localStorage.setItem('tadoku-paper-playground-v1', JSON.stringify({ viewer: 'participant', logs, contests: initialContests, joinedContests: [] }))
  show('/logs/new')
  const disclosure = screen.getByText('Use a recent log')
  expect(disclosure.closest('details')).not.toHaveAttribute('open')
  fireEvent.click(disclosure)
  const firstRows = screen.getAllByRole('button', { name: 'Use this log' })
  expect(firstRows).toHaveLength(5)
  expect(screen.getAllByText(/Recent entry \d+/).map(row => row.textContent)).toEqual(['Recent entry 10', 'Recent entry 9', 'Recent entry 8', 'Recent entry 7', 'Recent entry 6'])
  expect(screen.queryByText('Someone else’s entry')).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Show more' }))
  const expandedRows = screen.getAllByRole('button', { name: 'Use this log' })
  expect(expandedRows).toHaveLength(10)
  firstRows.forEach((row, index) => expect(expandedRows[index]).toBe(row))
  fireEvent.click(screen.getByRole('button', { name: 'Show more' }))
  expect(screen.getAllByRole('button', { name: 'Use this log' })).toHaveLength(11)
  expect(screen.getByRole('button', { name: 'All logs shown' })).toBeDisabled()
})


it('searches the full recent history, restores the newest entries when cleared, and never submits the log form', async () => {
  const user = userEvent.setup()
  const logs: SampleLog[] = Array.from({ length: 11 }, (_, index) => ({ ...initialLogs[0], id: `search-${index}`, title: `History entry ${index}`, tags: [], date: `2026-08-${String(index + 1).padStart(2, '0')}` }))
  logs[0] = { ...logs[0], title: 'Older novel', language: 'French', activity: 'Listening', unit: 'minutes', tags: ['bookclub'] }
  logs.push({ ...logs[0], id: 'another-reader', userId: 'mei', date: '2026-09-05' })
  localStorage.setItem('tadoku-paper-playground-v1', JSON.stringify({ viewer: 'participant', logs, contests: initialContests, joinedContests: [] }))
  show('/logs/new')
  fireEvent.change(screen.getByLabelText(/Pages read/), { target: { value: '20' } })
  fireEvent.click(screen.getByText('Use a recent log'))
  fireEvent.click(screen.getByRole('button', { name: 'Show more' }))
  expect(screen.getAllByRole('button', { name: 'Use this log' })).toHaveLength(10)

  const search = screen.getByRole('searchbox', { name: 'Search recent logs' })
  await user.type(search, '  OLDER NOVEL  {Enter}')
  expect(screen.getAllByRole('button', { name: 'Use this log' })).toHaveLength(1)
  expect(screen.getByText('Older novel')).toBeVisible()
  expect(screen.getByRole('button', { name: 'Next' })).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Save activity' })).not.toBeInTheDocument()
  expect(screen.getByLabelText(/Pages read/)).toHaveValue(20)
  expect(search).toHaveFocus()

  for (const query of ['BOOKCLUB', 'french', 'listening']) {
    await user.clear(search)
    await user.type(search, query)
    expect(screen.getAllByRole('button', { name: 'Use this log' })).toHaveLength(1)
    expect(screen.getByText('Older novel')).toBeVisible()
  }
  await user.clear(search)
  await user.type(search, 'no such entry')
  expect(screen.getByText('No matching logs.')).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Use this log' })).not.toBeInTheDocument()
  expect(search).toBeVisible()
  await user.clear(search)
  expect(screen.getAllByRole('button', { name: 'Use this log' })).toHaveLength(5)
  expect(screen.getAllByText(/History entry \d+/).map(row => row.textContent)).toEqual(['History entry 10', 'History entry 9', 'History entry 8', 'History entry 7', 'History entry 6'])
  await user.type(search, 'older')
  await user.click(screen.getByRole('button', { name: 'Use this log' }))
  expect(screen.getByLabelText('What did you read or listen to?')).toHaveValue('Older novel')
  expect(screen.getByLabelText(/Minutes listened/)).toHaveValue(null)
  await waitFor(() => expect(screen.getByLabelText(/Minutes listened/)).toHaveFocus())
})

it('reuses stable details, clears new quantities, preserves draft context and can undo the copy', async () => {
  const source: SampleLog = { ...initialLogs[0], title: 'One Piece volume 45', date: '2026-09-02', amount: 30, minutes: 50, tags: ['manga', 'fiction'], media: 'Manga', modifiers: ['Manga'] }
  localStorage.setItem('tadoku-paper-playground-v1', JSON.stringify({ viewer: 'participant', logs: [source], contests: initialContests, joinedContests: ['round5', 'reading-circle'] }))
  show('/logs/new')
  fireEvent.change(screen.getByRole('combobox', { name: 'Language' }), { target: { value: 'Spanish' } })
  fireEvent.change(screen.getByLabelText('What did you read or listen to?'), { target: { value: 'My unfinished draft' } })
  fireEvent.change(screen.getByLabelText(/Pages read/), { target: { value: '20' } })
  openMetadata()
  fireEvent.change(screen.getByLabelText('Time spent reading'), { target: { value: '25' } })
  fireEvent.change(screen.getByLabelText('Notes'), { target: { value: 'A thought for this new entry' } })
  await next()
  fireEvent.change(screen.getByLabelText(/Activity date/), { target: { value: '2026-09-03' } })
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByText('Use a recent log'))
  fireEvent.click(screen.getByRole('button', { name: 'Use this log' }))
  expect(screen.getByText('Use a recent log').closest('details')).not.toHaveAttribute('open')
  expect(screen.getByLabelText('What did you read or listen to?')).toHaveValue(source.title)
  expect(screen.getByRole('combobox', { name: 'Language' })).toHaveValue('Japanese')
  expect(screen.getByLabelText(/Pages read/)).toHaveValue(null)
  await waitFor(() => expect(screen.getByLabelText(/Pages read/)).toHaveFocus())
  expect(screen.getByRole('combobox', { name: 'Unit' })).toHaveValue('pages')
  expect(screen.getByRole('button', { name: /Manga ×/ })).toHaveAttribute('aria-pressed', 'true')
  expect(screen.getByLabelText('Time spent reading')).toHaveValue(null)
  expect(screen.getByLabelText('Notes')).toHaveValue('A thought for this new entry')
  expect(screen.getByRole('button', { name: 'Remove manga' })).toBeVisible()
  expect(screen.getByRole('button', { name: 'Remove fiction' })).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Undo' }))
  expect(screen.getByLabelText('What did you read or listen to?')).toHaveValue('My unfinished draft')
  expect(screen.getByRole('combobox', { name: 'Language' })).toHaveValue('Spanish')
  expect(screen.getByLabelText(/Pages read/)).toHaveValue(20)
  expect(screen.getByLabelText('Time spent reading')).toHaveValue(25)
  expect(screen.getByRole('button', { name: /Manga ×/ })).toHaveAttribute('aria-pressed', 'false')
  expect(screen.queryByRole('button', { name: 'Remove manga' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByText('Use a recent log'))
  fireEvent.click(screen.getByRole('button', { name: 'Use this log' }))
  fireEvent.change(screen.getByLabelText(/Pages read/), { target: { value: '9' } })
  await next()
  expect(screen.getByLabelText(/Activity date/)).toHaveValue('2026-09-03')
  expect(screen.getByRole('checkbox', { name: '2026 Round 5' })).not.toBeChecked()
  fireEvent.click(screen.getByRole('button', { name: 'Save activity' }))
  const saved = JSON.parse((await screen.findByLabelText('Saved record')).textContent || '{}')
  expect(saved).toMatchObject({ title: source.title, language: source.language, activity: source.activity, unit: source.unit, tags: source.tags, modifiers: source.modifiers, media: source.media, amount: 9, note: 'A thought for this new entry', date: '2026-09-03', submissions: [] })
  expect(saved.minutes).toBeUndefined()
})

it('drops incompatible modifiers when changing activity or reading unit and saves the selected unit', async () => {
  show('/logs/new')
  fireEvent.click(screen.getByRole('button', { name: /Manga ×/ }))
  fireEvent.click(screen.getByRole('button', { name: /Two column ×/ }))
  expect(screen.getByRole('button', { name: /Manga ×/ })).toHaveAttribute('aria-pressed', 'false')
  fireEvent.change(screen.getByRole('combobox', { name: 'Activity' }), { target: { value: 'Listening' } })
  expect(screen.queryByRole('button', { name: /Two column ×/ })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: /Passive listening/ }))
  fireEvent.change(screen.getByRole('combobox', { name: 'Activity' }), { target: { value: 'Reading' } })
  expect(screen.getByRole('button', { name: /Two column ×/ })).toHaveAttribute('aria-pressed', 'false')
  fireEvent.click(screen.getByRole('button', { name: /Manga ×/ }))
  fireEvent.change(screen.getByRole('combobox', { name: 'Unit' }), { target: { value: 'sentences' } })
  expect(screen.queryByRole('button', { name: /Manga ×/ })).not.toBeInTheDocument()
  fireEvent.change(screen.getByLabelText(/Sentences read/), { target: { value: '18' } })
  await next()
  fireEvent.click(screen.getByRole('button', { name: 'Save activity' }))
  const saved = JSON.parse((await screen.findByLabelText('Saved record')).textContent || '{}')
  expect(saved).toMatchObject({ activity: 'Reading', unit: 'sentences', amount: 18, modifiers: [] })
})

it('copies a listening entry without its previous duration and saves its compatible modifier', async () => {
  const source: SampleLog = { ...initialLogs[1], modifiers: ['Passive listening'] }
  localStorage.setItem('tadoku-paper-playground-v1', JSON.stringify({ viewer: 'participant', logs: [source], contests: initialContests, joinedContests: [] }))
  show('/logs/new')
  fireEvent.click(screen.getByText('Use a recent log'))
  fireEvent.click(screen.getByRole('button', { name: 'Use this log' }))
  expect(screen.getByRole('combobox', { name: 'Activity' })).toHaveValue('Listening')
  expect(screen.getByLabelText(/Minutes listened/)).toHaveValue(null)
  expect(screen.getByRole('button', { name: /Passive listening/ })).toHaveAttribute('aria-pressed', 'true')
  openMetadata()
  expect(screen.queryByLabelText('Time spent reading')).not.toBeInTheDocument()
  fireEvent.change(screen.getByLabelText(/Minutes listened/), { target: { value: '15' } })
  await next()
  fireEvent.click(screen.getByRole('button', { name: 'Save activity' }))
  const saved = JSON.parse((await screen.findByLabelText('Saved record')).textContent || '{}')
  expect(saved).toMatchObject({ activity: 'Listening', unit: 'minutes', amount: 15, modifiers: ['Passive listening'], submissions: [] })
})

it('remembers whether metadata should start expanded on subsequent forms', async () => {
  let form = show('/logs/new')
  expect(screen.getByText(/^Metadata/).closest('details')).not.toHaveAttribute('open')
  openMetadata()
  fireEvent.click(screen.getByRole('checkbox', { name: 'Expand section by default' }))
  form.unmount()
  form = show('/logs/new')
  expect(screen.getByText(/^Metadata/).closest('details')).toHaveAttribute('open')
  expect(screen.getByRole('checkbox', { name: 'Expand section by default' })).toBeChecked()
  fireEvent.click(screen.getByRole('checkbox', { name: 'Expand section by default' }))
  form.unmount()
  show('/logs/new')
  expect(screen.getByText(/^Metadata/).closest('details')).not.toHaveAttribute('open')
})


it('adds a custom tag without advancing the log form or losing input focus', async () => {
  const user = userEvent.setup()
  show('/logs/new')
  await user.type(screen.getByLabelText(/Pages read/), '12')
  await user.click(screen.getByText(/^Metadata/))
  const input = screen.getByRole('combobox', { name: 'Tags' })
  await user.type(input, 'train reading{Enter}')
  expect(screen.getByRole('button', { name: 'Remove train reading' })).toBeInTheDocument()
  expect(input).toHaveFocus()
  expect(input).toHaveValue('')
  expect(screen.getByRole('button', { name: 'Next' })).toBeVisible()
  await next()
  await user.click(screen.getByRole('button', { name: 'Save activity' }))
  const saved = JSON.parse((await screen.findByLabelText('Saved record')).textContent || '{}')
  expect(saved.tags).toEqual(['train reading'])
})
