load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "observability",
    srcs = [
        "scoring_shadow.go",
        "server.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/immersion-api/observability",
    visibility = ["//visibility:public"],
    deps = ["//services/immersion-api/domain"],
)

go_test(
    name = "observability_test",
    srcs = ["scoring_shadow_test.go"],
    embed = [":observability"],
    deps = [
        "//services/immersion-api/domain",
        "@com_github_google_uuid//:uuid",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
