load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "observability",
    srcs = [
        "leaderboard_cache.go",
        "scoring_shadow.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/immersion-api/observability",
    visibility = ["//visibility:public"],
    deps = [
        "//services/immersion-api/domain",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)

go_test(
    name = "observability_test",
    srcs = [
        "leaderboard_cache_test.go",
        "scoring_shadow_test.go",
    ],
    embed = [":observability"],
    deps = [
        "//services/immersion-api/domain",
        "@com_github_google_uuid//:uuid",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
