apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tdk-dev-keto
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: keto-config
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-20"
    files:
      - keto.yaml
      - namespaces.keto.ts
