load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "legacy",
    testonly = True,
    srcs = ["content.go"],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/e2e/legacy",
    visibility = ["//services/tadoku-api/e2e:__pkg__"],
    deps = [
        "//services/common/authz/roles",
        "//services/common/client/keto",
        "//services/common/middleware",
        "//services/content-api/domain",
        "//services/content-api/http/rest",
        "//services/content-api/http/rest/openapi",
        "//services/content-api/storage/postgres",
        "@com_github_labstack_echo_v4//:echo",
        "@com_github_labstack_echo_v4//middleware",
    ],
)

go_test(
    name = "legacy_test",
    srcs = ["proxy_identity_test.go"],
    deps = [
        "//services/common/domain",
        "//services/common/middleware",
        "//services/tadoku-api/transport/http",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_github_labstack_echo_v4//:echo",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)
