load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

go_library(
    name = "image-webhook-gateway_lib",
    srcs = ["main.go"],
    importpath = "github.com/tadoku/tadoku/services/image-webhook-gateway",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "image-webhook-gateway",
    embed = [":image-webhook-gateway_lib"],
    pure = "on",
    static = "on",
    visibility = ["//visibility:public"],
)

go_test(
    name = "image-webhook-gateway_test",
    srcs = ["main_test.go"],
    embed = [":image-webhook-gateway_lib"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)

pkg_tar(
    name = "app_layer",
    srcs = [":image-webhook-gateway"],
    mode = "0755",
    package_dir = "/",
)

oci_image(
    name = "image",
    base = "@distroless_base_linux_amd64",
    entrypoint = ["/image-webhook-gateway"],
    tars = [":app_layer"],
)

oci_load(
    name = "load",
    image = ":image",
    repo_tags = [
        "ghcr.io/tadoku/tadoku/image-webhook-gateway:latest",
        "bazel/services/image-webhook-gateway:latest",
    ],
    visibility = ["//visibility:public"],
)

oci_push(
    name = "dev_push",
    image = ":image",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push",
    image = ":image",
    remote_tags = [
        "latest",
        "prod",
    ],
    repository = "ghcr.io/tadoku/tadoku/image-webhook-gateway",
    visibility = ["//visibility:public"],
)
