load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kratos",
    srcs = ["client.go"],
    importpath = "github.com/tadoku/tadoku/services/common/client/kratos",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_google_uuid//:uuid",
        "@com_github_ory_kratos_client_go//:kratos-client-go",
    ],
)

go_test(
    name = "kratos_test",
    srcs = ["client_test.go"],
    deps = [
        ":kratos",
        "@com_github_google_uuid//:uuid",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
