// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: activities.sql

package postgres

import (
	"context"
)

const listActivities = `-- name: ListActivities :many
select
  id,
  name,
  "default"
from log_activities
order by name asc
`

func (q *Queries) ListActivities(ctx context.Context) ([]LogActivity, error) {
	rows, err := q.db.QueryContext(ctx, listActivities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogActivity
	for rows.Next() {
		var i LogActivity
		if err := rows.Scan(&i.ID, &i.Name, &i.Default); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
