// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: languages.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createLanguage = `-- name: CreateLanguage :exec
insert into languages (code, name) values ($1, $2)
`

type CreateLanguageParams struct {
	Code string
	Name string
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) error {
	_, err := q.db.ExecContext(ctx, createLanguage, arg.Code, arg.Name)
	return err
}

const getLanguagesByCode = `-- name: GetLanguagesByCode :many
select
  code,
  name
from languages
where
  code = any($1::varchar[])
order by name asc
`

func (q *Queries) GetLanguagesByCode(ctx context.Context, languageCodes []string) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, getLanguagesByCode, pq.Array(languageCodes))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctLanguageCodesForUser = `-- name: ListDistinctLanguageCodesForUser :many
select distinct language_code
from logs
where user_id = $1 and deleted_at is null
`

func (q *Queries) ListDistinctLanguageCodesForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctLanguageCodesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var language_code string
		if err := rows.Scan(&language_code); err != nil {
			return nil, err
		}
		items = append(items, language_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many
select
  code,
  name
from languages
order by name asc
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguagesForContest = `-- name: ListLanguagesForContest :many
select
  code,
  name
from languages
left join contests
  on languages.code = any(language_code_allow_list) or language_code_allow_list is null
where
  id = $1
order by name asc
`

func (q *Queries) ListLanguagesForContest(ctx context.Context, contestID uuid.UUID) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, listLanguagesForContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLanguage = `-- name: UpdateLanguage :exec
update languages set name = $1 where code = $2
`

type UpdateLanguageParams struct {
	Name string
	Code string
}

func (q *Queries) UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) error {
	_, err := q.db.ExecContext(ctx, updateLanguage, arg.Name, arg.Code)
	return err
}
