// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: leaderboard.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const contestLeaderboardAllScores = `-- name: ContestLeaderboardAllScores :many
select
  cr.user_id,
  coalesce(scores.score, 0)::real as score
from contest_registrations cr
left join (
  select
    logs.user_id,
    sum(coalesce(contest_logs.computed_score, contest_logs.score)) as score
  from contest_logs
  inner join logs on logs.id = contest_logs.log_id
  where
    contest_logs.contest_id = $1
    and logs.deleted_at is null
  group by logs.user_id
) scores on scores.user_id = cr.user_id
where
  cr.contest_id = $1
  and cr.deleted_at is null
`

type ContestLeaderboardAllScoresRow struct {
	UserID uuid.UUID
	Score  float32
}

// Returns all user scores for a contest without pagination/ranking.
// Used for rebuilding the Redis leaderboard sorted set.
func (q *Queries) ContestLeaderboardAllScores(ctx context.Context, contestID uuid.UUID) ([]ContestLeaderboardAllScoresRow, error) {
	rows, err := q.db.QueryContext(ctx, contestLeaderboardAllScores, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestLeaderboardAllScoresRow
	for rows.Next() {
		var i ContestLeaderboardAllScoresRow
		if err := rows.Scan(&i.UserID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalLeaderboard = `-- name: GlobalLeaderboard :many
with leaderboard as (
  select
    user_id,
    sum(coalesce(computed_score, score)) as score
  from logs
  where
    eligible_official_leaderboard = true
    and logs.deleted_at is null
    and (logs.language_code = $3 or $3 is null)
    and (logs.log_activity_id = $4::integer or $4 is null)
  group by user_id
), ranked_leaderboard as (
  select
    user_id,
    score,
    rank() over(order by score desc) as "rank"
  from leaderboard
  where score > 0
), enriched_leaderboard as (
  select
    rank() over(order by coalesce(ranked_leaderboard.score, 0) desc) as "rank",
    ranked_leaderboard.user_id,
    users.display_name::varchar as user_display_name,
    coalesce(ranked_leaderboard.score, 0)::real as score
  from ranked_leaderboard
  inner join users on users.id = ranked_leaderboard.user_id
  order by
    score desc,
    user_display_name asc
)
select
  rank, user_id, user_display_name, score,
  coalesce((
    "rank" = lag("rank", 1, -1::bigint) over (order by "rank")
    or "rank" = lead("rank", 1, -1::bigint) over (order by "rank")
  ), false)::boolean as is_tie,
  (select count(user_id) from enriched_leaderboard) as total_size
from enriched_leaderboard
limit $2
offset $1
`

type GlobalLeaderboardParams struct {
	StartFrom    int32
	PageSize     int32
	LanguageCode sql.NullString
	ActivityID   sql.NullInt32
}

type GlobalLeaderboardRow struct {
	Rank            int64
	UserID          uuid.UUID
	UserDisplayName string
	Score           float32
	IsTie           bool
	TotalSize       int64
}

func (q *Queries) GlobalLeaderboard(ctx context.Context, arg GlobalLeaderboardParams) ([]GlobalLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, globalLeaderboard,
		arg.StartFrom,
		arg.PageSize,
		arg.LanguageCode,
		arg.ActivityID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalLeaderboardRow
	for rows.Next() {
		var i GlobalLeaderboardRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.UserDisplayName,
			&i.Score,
			&i.IsTie,
			&i.TotalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalLeaderboardAllScores = `-- name: GlobalLeaderboardAllScores :many
select
  user_id,
  sum(coalesce(computed_score, score))::real as score
from logs
where
  eligible_official_leaderboard = true
  and deleted_at is null
group by user_id
having sum(coalesce(computed_score, score)) > 0
`

type GlobalLeaderboardAllScoresRow struct {
	UserID uuid.UUID
	Score  float32
}

// Returns all user scores globally without pagination/ranking.
// Used for rebuilding the Redis leaderboard sorted set.
func (q *Queries) GlobalLeaderboardAllScores(ctx context.Context) ([]GlobalLeaderboardAllScoresRow, error) {
	rows, err := q.db.QueryContext(ctx, globalLeaderboardAllScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalLeaderboardAllScoresRow
	for rows.Next() {
		var i GlobalLeaderboardAllScoresRow
		if err := rows.Scan(&i.UserID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardForContest = `-- name: LeaderboardForContest :many
with leaderboard as (
  select
    logs.user_id,
    sum(coalesce(contest_logs.computed_score, contest_logs.score)) as score
  from contest_logs
  inner join logs
    on logs.id = contest_logs.log_id
  where
    contest_logs.contest_id = $3
    and logs.deleted_at is null
    and (logs.language_code = $4 or $4 is null)
    and (logs.log_activity_id = $5::integer or $5 is null)
  group by logs.user_id
), ranked_leaderboard as (
  select
    user_id,
    score,
    rank() over(order by score desc) as "rank"
  from leaderboard
), registrations as (
  select
    contest_registrations.id,
    user_id,
    users.display_name as user_display_name,
    contest_registrations.created_at
  from contest_registrations
  inner join users on users.id = contest_registrations.user_id
  where
    contest_id = $3
    and deleted_at is null
    and ($4 = any(language_codes) or $4 is null)
), enriched_leaderboard as (
  select
    rank() over(order by coalesce(ranked_leaderboard.score, 0) desc) as "rank",
    registrations.user_id,
    registrations.user_display_name,
    coalesce(ranked_leaderboard.score, 0)::real as score,
    (select count(registrations.user_id) from registrations) as total_size
  from registrations
  left join ranked_leaderboard using(user_id)
  order by
    score desc,
    registrations.created_at asc
)
select
  rank, user_id, user_display_name, score, total_size,
  coalesce((
    "rank" = lag("rank", 1, -1::bigint) over (order by "rank")
    or "rank" = lead("rank", 1, -1::bigint) over (order by "rank")
  ), false)::boolean as is_tie
from enriched_leaderboard
limit $2
offset $1
`

type LeaderboardForContestParams struct {
	StartFrom    int32
	PageSize     int32
	ContestID    uuid.UUID
	LanguageCode sql.NullString
	ActivityID   sql.NullInt32
}

type LeaderboardForContestRow struct {
	Rank            int64
	UserID          uuid.UUID
	UserDisplayName string
	Score           float32
	TotalSize       int64
	IsTie           bool
}

func (q *Queries) LeaderboardForContest(ctx context.Context, arg LeaderboardForContestParams) ([]LeaderboardForContestRow, error) {
	rows, err := q.db.QueryContext(ctx, leaderboardForContest,
		arg.StartFrom,
		arg.PageSize,
		arg.ContestID,
		arg.LanguageCode,
		arg.ActivityID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardForContestRow
	for rows.Next() {
		var i LeaderboardForContestRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.UserDisplayName,
			&i.Score,
			&i.TotalSize,
			&i.IsTie,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userContestScore = `-- name: UserContestScore :one
select
  coalesce(sum(coalesce(contest_logs.computed_score, contest_logs.score)), 0)::real as score
from contest_logs
inner join logs on logs.id = contest_logs.log_id
where
  contest_logs.contest_id = $1
  and logs.user_id = $2
  and logs.deleted_at is null
`

type UserContestScoreParams struct {
	ContestID uuid.UUID
	UserID    uuid.UUID
}

// Returns a single user's total score for a contest.
// Used for updating a user's score in the Redis leaderboard.
func (q *Queries) UserContestScore(ctx context.Context, arg UserContestScoreParams) (float32, error) {
	row := q.db.QueryRowContext(ctx, userContestScore, arg.ContestID, arg.UserID)
	var score float32
	err := row.Scan(&score)
	return score, err
}

const userGlobalScore = `-- name: UserGlobalScore :one
select
  coalesce(sum(coalesce(computed_score, score)), 0)::real as score
from logs
where
  user_id = $1
  and eligible_official_leaderboard = true
  and deleted_at is null
`

// Returns a single user's total global score (official logs only).
// Used for updating a user's score in the Redis leaderboard.
func (q *Queries) UserGlobalScore(ctx context.Context, userID uuid.UUID) (float32, error) {
	row := q.db.QueryRowContext(ctx, userGlobalScore, userID)
	var score float32
	err := row.Scan(&score)
	return score, err
}

const userYearlyScore = `-- name: UserYearlyScore :one
select
  coalesce(sum(coalesce(computed_score, score)), 0)::real as score
from logs
where
  year = $1
  and user_id = $2
  and eligible_official_leaderboard = true
  and deleted_at is null
`

type UserYearlyScoreParams struct {
	Year   int16
	UserID uuid.UUID
}

// Returns a single user's total score for a year (official logs only).
// Used for updating a user's score in the Redis leaderboard.
func (q *Queries) UserYearlyScore(ctx context.Context, arg UserYearlyScoreParams) (float32, error) {
	row := q.db.QueryRowContext(ctx, userYearlyScore, arg.Year, arg.UserID)
	var score float32
	err := row.Scan(&score)
	return score, err
}

const yearlyLeaderboard = `-- name: YearlyLeaderboard :many
with leaderboard as (
  select
    user_id,
    sum(coalesce(computed_score, score)) as score
  from logs
  where
    logs.year = $3
    and eligible_official_leaderboard = true
    and logs.deleted_at is null
    and (logs.language_code = $4 or $4 is null)
    and (logs.log_activity_id = $5::integer or $5 is null)
  group by user_id
), ranked_leaderboard as (
  select
    user_id,
    score,
    rank() over(order by score desc) as "rank"
  from leaderboard
), enriched_leaderboard as (
  select
    rank() over(order by coalesce(ranked_leaderboard.score, 0) desc) as "rank",
    ranked_leaderboard.user_id,
    users.display_name::varchar as user_display_name,
    coalesce(ranked_leaderboard.score, 0)::real as score
  from ranked_leaderboard
  inner join users on users.id = ranked_leaderboard.user_id
  order by
    score desc,
    user_display_name asc
)
select
  rank, user_id, user_display_name, score,
  coalesce((
    "rank" = lag("rank", 1, -1::bigint) over (order by "rank")
    or "rank" = lead("rank", 1, -1::bigint) over (order by "rank")
  ), false)::boolean as is_tie,
  (select count(user_id) from enriched_leaderboard) as total_size
from enriched_leaderboard
limit $2
offset $1
`

type YearlyLeaderboardParams struct {
	StartFrom    int32
	PageSize     int32
	Year         int16
	LanguageCode sql.NullString
	ActivityID   sql.NullInt32
}

type YearlyLeaderboardRow struct {
	Rank            int64
	UserID          uuid.UUID
	UserDisplayName string
	Score           float32
	IsTie           bool
	TotalSize       int64
}

func (q *Queries) YearlyLeaderboard(ctx context.Context, arg YearlyLeaderboardParams) ([]YearlyLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, yearlyLeaderboard,
		arg.StartFrom,
		arg.PageSize,
		arg.Year,
		arg.LanguageCode,
		arg.ActivityID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YearlyLeaderboardRow
	for rows.Next() {
		var i YearlyLeaderboardRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.UserDisplayName,
			&i.Score,
			&i.IsTie,
			&i.TotalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const yearlyLeaderboardAllScores = `-- name: YearlyLeaderboardAllScores :many
select
  user_id,
  sum(coalesce(computed_score, score))::real as score
from logs
where
  year = $1
  and eligible_official_leaderboard = true
  and deleted_at is null
group by user_id
having sum(coalesce(computed_score, score)) > 0
`

type YearlyLeaderboardAllScoresRow struct {
	UserID uuid.UUID
	Score  float32
}

// Returns all user scores for a year without pagination/ranking.
// Used for rebuilding the Redis leaderboard sorted set.
func (q *Queries) YearlyLeaderboardAllScores(ctx context.Context, year int16) ([]YearlyLeaderboardAllScoresRow, error) {
	rows, err := q.db.QueryContext(ctx, yearlyLeaderboardAllScores, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YearlyLeaderboardAllScoresRow
	for rows.Next() {
		var i YearlyLeaderboardAllScoresRow
		if err := rows.Scan(&i.UserID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
