// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: leaderboard_outbox.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const cleanupProcessedOutboxEvents = `-- name: CleanupProcessedOutboxEvents :exec
delete from leaderboard_outbox
where processed_at is not null
  and processed_at < $1
`

func (q *Queries) CleanupProcessedOutboxEvents(ctx context.Context, before time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupProcessedOutboxEvents, before)
	return err
}

const fetchAndLockOutboxEvents = `-- name: FetchAndLockOutboxEvents :many
select id, event_type, user_id, contest_id, year
from leaderboard_outbox
where processed_at is null
order by id
for update skip locked
limit $1
`

type FetchAndLockOutboxEventsRow struct {
	ID        int64
	EventType string
	UserID    uuid.UUID
	ContestID uuid.NullUUID
	Year      sql.NullInt16
}

func (q *Queries) FetchAndLockOutboxEvents(ctx context.Context, batchSize int32) ([]FetchAndLockOutboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchAndLockOutboxEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchAndLockOutboxEventsRow
	for rows.Next() {
		var i FetchAndLockOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.UserID,
			&i.ContestID,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLeaderboardOutboxEvent = `-- name: InsertLeaderboardOutboxEvent :exec
insert into leaderboard_outbox (event_type, user_id, contest_id, year)
values ($1, $2, $3, $4)
`

type InsertLeaderboardOutboxEventParams struct {
	EventType string
	UserID    uuid.UUID
	ContestID uuid.NullUUID
	Year      sql.NullInt16
}

func (q *Queries) InsertLeaderboardOutboxEvent(ctx context.Context, arg InsertLeaderboardOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, insertLeaderboardOutboxEvent,
		arg.EventType,
		arg.UserID,
		arg.ContestID,
		arg.Year,
	)
	return err
}

const markOutboxEventsProcessed = `-- name: MarkOutboxEventsProcessed :exec
update leaderboard_outbox
set processed_at = now()
where id = any($1::bigint[])
`

func (q *Queries) MarkOutboxEventsProcessed(ctx context.Context, ids []int64) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventsProcessed, pq.Array(ids))
	return err
}
