// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: log_tags.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteLogTagsForLog = `-- name: DeleteLogTagsForLog :exec
delete from log_tags where log_id = $1
`

func (q *Queries) DeleteLogTagsForLog(ctx context.Context, logID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLogTagsForLog, logID)
	return err
}

const insertLogTag = `-- name: InsertLogTag :exec
insert into log_tags (log_id, user_id, tag)
values ($1, $2, $3)
on conflict do nothing
`

type InsertLogTagParams struct {
	LogID  uuid.UUID
	UserID uuid.UUID
	Tag    string
}

func (q *Queries) InsertLogTag(ctx context.Context, arg InsertLogTagParams) error {
	_, err := q.db.ExecContext(ctx, insertLogTag, arg.LogID, arg.UserID, arg.Tag)
	return err
}

const listDefaultTagsMatching = `-- name: ListDefaultTagsMatching :many
select name as tag
from log_default_tags
where name ilike '%' || $1 || '%'
order by name
limit 30
`

func (q *Queries) ListDefaultTagsMatching(ctx context.Context, query sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDefaultTagsMatching, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagSuggestionsForUser = `-- name: ListTagSuggestionsForUser :many
select tag, count(*) as usage_count
from log_tags
where user_id = $1
  and tag ilike '%' || $2 || '%'
group by tag
order by usage_count desc, tag
limit 30
`

type ListTagSuggestionsForUserParams struct {
	UserID uuid.UUID
	Query  sql.NullString
}

type ListTagSuggestionsForUserRow struct {
	Tag        string
	UsageCount int64
}

func (q *Queries) ListTagSuggestionsForUser(ctx context.Context, arg ListTagSuggestionsForUserParams) ([]ListTagSuggestionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagSuggestionsForUser, arg.UserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagSuggestionsForUserRow
	for rows.Next() {
		var i ListTagSuggestionsForUserRow
		if err := rows.Scan(&i.Tag, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
