// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: moderation.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createModerationAuditLog = `-- name: CreateModerationAuditLog :exec
insert into moderation_audit_log (
  user_id,
  action,
  metadata,
  description
) values (
  $1,
  $2,
  $3,
  $4
)
`

type CreateModerationAuditLogParams struct {
	UserID      uuid.UUID
	Action      string
	Metadata    json.RawMessage
	Description sql.NullString
}

func (q *Queries) CreateModerationAuditLog(ctx context.Context, arg CreateModerationAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createModerationAuditLog,
		arg.UserID,
		arg.Action,
		arg.Metadata,
		arg.Description,
	)
	return err
}
