// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Contest struct {
	ID                      uuid.UUID
	OwnerUserID             uuid.UUID
	OwnerUserDisplayName    string
	Private                 bool
	ContestStart            time.Time
	ContestEnd              time.Time
	RegistrationEnd         time.Time
	Title                   string
	Description             sql.NullString
	LanguageCodeAllowList   []string
	ActivityTypeIDAllowList []int32
	Official                bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
	DeletedAt               sql.NullTime
}

type ContestLog struct {
	ContestID       uuid.UUID
	LogID           uuid.UUID
	Amount          sql.NullFloat64
	Modifier        sql.NullFloat64
	Score           sql.NullFloat64
	DurationSeconds sql.NullInt32
	ComputedScore   sql.NullFloat64
}

type ContestRegistration struct {
	ID            uuid.UUID
	ContestID     uuid.UUID
	UserID        uuid.UUID
	LanguageCodes []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type Language struct {
	// See https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)
	Code string
	Name string
}

type LeaderboardOutbox struct {
	ID          int64
	EventType   string
	UserID      uuid.UUID
	ContestID   uuid.NullUUID
	Year        sql.NullInt16
	CreatedAt   time.Time
	ProcessedAt sql.NullTime
}

type Log struct {
	ID                          uuid.UUID
	UserID                      uuid.UUID
	LanguageCode                string
	LogActivityID               int16
	UnitID                      uuid.NullUUID
	Description                 sql.NullString
	Amount                      sql.NullFloat64
	Modifier                    sql.NullFloat64
	Score                       float32
	EligibleOfficialLeaderboard bool
	Year                        int16
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	DeletedAt                   sql.NullTime
	DurationSeconds             sql.NullInt32
	ComputedScore               sql.NullFloat64
}

type LogActivity struct {
	ID           int32
	Name         string
	Default      bool
	TimeModifier float32
	InputType    string
}

type LogDefaultTag struct {
	ID   uuid.UUID
	Name string
}

type LogTag struct {
	LogID     uuid.UUID
	UserID    uuid.UUID
	Tag       string
	CreatedAt time.Time
}

type LogUnit struct {
	ID            uuid.UUID
	LogActivityID int16
	Name          string
	Modifier      float32
	LanguageCode  sql.NullString
}

type ModerationAuditLog struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Action      string
	Metadata    json.RawMessage
	Description sql.NullString
	CreatedAt   time.Time
}

type User struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserRole struct {
	UserID    uuid.UUID
	Role      string
	UpdatedAt time.Time
}
