// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Contest struct {
	ID                      uuid.UUID
	OwnerUserID             uuid.UUID
	OwnerUserDisplayName    string
	Private                 bool
	ContestStart            time.Time
	ContestEnd              time.Time
	RegistrationEnd         time.Time
	Title                   string
	Description             sql.NullString
	LanguageCodeAllowList   []string
	ActivityTypeIDAllowList []int32
	Official                bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
	DeletedAt               sql.NullTime
}

type ContestLog struct {
	ContestID uuid.UUID
	LogID     uuid.UUID
}

type ContestRegistration struct {
	ID              uuid.UUID
	ContestID       uuid.UUID
	UserID          uuid.UUID
	UserDisplayName string
	LanguageCodes   []string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type Language struct {
	// See https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)
	Code string
	Name string
}

type Log struct {
	ID                          uuid.UUID
	UserID                      uuid.UUID
	LanguageCode                string
	LogActivityID               int16
	UnitID                      uuid.UUID
	Tags                        []string
	Description                 sql.NullString
	Amount                      float32
	Modifier                    float32
	Score                       float32
	EligibleOfficialLeaderboard bool
	Year                        int16
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	DeletedAt                   sql.NullTime
}

type LogActivity struct {
	ID      int32
	Name    string
	Default bool
}

type LogTag struct {
	ID            uuid.UUID
	LogActivityID int16
	Name          string
}

type LogUnit struct {
	ID            uuid.UUID
	LogActivityID int16
	Name          string
	Modifier      float32
	LanguageCode  sql.NullString
}
