// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: scoring.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const findActivePlatformScoringRuleSet = `-- name: FindActivePlatformScoringRuleSet :one
select scoring_rule_sets.id, scoring_rule_sets.scope, scoring_rule_sets.contest_id, scoring_rule_sets.version, scoring_rule_sets.status, scoring_rule_sets.mode, scoring_rule_sets.fallback_rule_set_id, scoring_rule_sets.created_at, scoring_rule_sets.published_at
from platform_scoring_config
inner join scoring_rule_sets
  on scoring_rule_sets.id = platform_scoring_config.active_rule_set_id
where platform_scoring_config.singleton = true
`

func (q *Queries) FindActivePlatformScoringRuleSet(ctx context.Context) (ScoringRuleSet, error) {
	row := q.db.QueryRowContext(ctx, findActivePlatformScoringRuleSet)
	var i ScoringRuleSet
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ContestID,
		&i.Version,
		&i.Status,
		&i.Mode,
		&i.FallbackRuleSetID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const findScoringRuleSetByID = `-- name: FindScoringRuleSetByID :one
select id, scope, contest_id, version, status, mode, fallback_rule_set_id, created_at, published_at
from scoring_rule_sets
where id = $1
`

func (q *Queries) FindScoringRuleSetByID(ctx context.Context, id uuid.UUID) (ScoringRuleSet, error) {
	row := q.db.QueryRowContext(ctx, findScoringRuleSetByID, id)
	var i ScoringRuleSet
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ContestID,
		&i.Version,
		&i.Status,
		&i.Mode,
		&i.FallbackRuleSetID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listScoringRulesForRuleSet = `-- name: ListScoringRulesForRuleSet :many
select id, rule_set_id, priority, stackable, activity_id, unit_key, language_code, tag, score_source, rate
from scoring_rules
where rule_set_id = $1
order by priority asc
`

func (q *Queries) ListScoringRulesForRuleSet(ctx context.Context, ruleSetID uuid.UUID) ([]ScoringRule, error) {
	rows, err := q.db.QueryContext(ctx, listScoringRulesForRuleSet, ruleSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoringRule
	for rows.Next() {
		var i ScoringRule
		if err := rows.Scan(
			&i.ID,
			&i.RuleSetID,
			&i.Priority,
			&i.Stackable,
			&i.ActivityID,
			&i.UnitKey,
			&i.LanguageCode,
			&i.Tag,
			&i.ScoreSource,
			&i.Rate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
