// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: tags.sql

package postgres

import (
	"context"
)

const listTags = `-- name: ListTags :many
select
  id,
  name
from log_default_tags
order by name asc
`

func (q *Queries) ListTags(ctx context.Context) ([]LogDefaultTag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogDefaultTag
	for rows.Next() {
		var i LogDefaultTag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
