// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: units.sql

package postgres

import (
	"context"
)

const listUnits = `-- name: ListUnits :many
select
  id,
  log_activity_id,
  name,
  modifier,
  language_code
from log_units
order by log_activity_id asc
`

func (q *Queries) ListUnits(ctx context.Context) ([]LogUnit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogUnit
	for rows.Next() {
		var i LogUnit
		if err := rows.Scan(
			&i.ID,
			&i.LogActivityID,
			&i.Name,
			&i.Modifier,
			&i.LanguageCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
