// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user_roles.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserRole = `-- name: DeleteUserRole :exec
delete from user_roles where user_id = $1
`

func (q *Queries) DeleteUserRole(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserRole, userID)
	return err
}

const getUserRoleByUserID = `-- name: GetUserRoleByUserID :one
select role from user_roles where user_id = $1
`

func (q *Queries) GetUserRoleByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleByUserID, userID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const upsertUserRole = `-- name: UpsertUserRole :exec
insert into user_roles (
  user_id,
  role,
  updated_at
) values (
  $1,
  $2,
  now()
) on conflict (user_id) do update set
  role = $2,
  updated_at = now()
`

type UpsertUserRoleParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) UpsertUserRole(ctx context.Context, arg UpsertUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserRole, arg.UserID, arg.Role)
	return err
}
