// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user_tags.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const listDefaultTags = `-- name: ListDefaultTags :many
select name as tag
from log_default_tags
order by name asc
`

func (q *Queries) ListDefaultTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDefaultTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTags = `-- name: ListUserTags :many
select tag, count(*) as usage_count
from log_tags
where user_id = $1
  and ($2::text = '' or starts_with(tag, $2))
group by tag
order by usage_count desc, tag asc
limit $3 offset $4
`

type ListUserTagsParams struct {
	UserID  uuid.UUID
	Column2 string
	Limit   int32
	Offset  int32
}

type ListUserTagsRow struct {
	Tag        string
	UsageCount int64
}

func (q *Queries) ListUserTags(ctx context.Context, arg ListUserTagsParams) ([]ListUserTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserTags,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTagsRow
	for rows.Next() {
		var i ListUserTagsRow
		if err := rows.Scan(&i.Tag, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
