// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user_roles_list.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const listAllUserRoles = `-- name: ListAllUserRoles :many
select user_id, role from user_roles
`

type ListAllUserRolesRow struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) ListAllUserRoles(ctx context.Context) ([]ListAllUserRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllUserRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUserRolesRow
	for rows.Next() {
		var i ListAllUserRolesRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
