apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-api
  labels:
    app: profile-api
spec:
  selector:
    matchLabels:
      app: profile-api
  template:
    metadata:
      labels:
        app: profile-api
    spec:
      serviceAccountName: default
      initContainers:
        - name: migrations
          image: profile-api-migrate-image
          command: ['/migrate']
          args: ['-source', 'file:///migrations', '-database', '$(DATABASE_URL)', 'up']
          env:
          - name: DATABASE_URL
            value: "postgres://profile:foobar@postgres-profile/profile?sslmode=disable"
      containers:
      - name: profile-api
        image: profile-api-image
        ports:
        - containerPort: 8000
        env:
          - name: API_POSTGRES_URL
            value: "postgres://profile:foobar@postgres-profile/profile?sslmode=disable"
          - name: API_PORT
            value: "8000"
          - name: API_JWKS
            value: "http://oathkeeper-api:4456/.well-known/jwks.json"
          - name: API_OATHKEEPER_URL
            value: "http://oathkeeper-api:4456"
          - name: SERVICE_NAME
            value: "profile-api"
        volumeMounts:
        - name: tadoku-permissions
          mountPath: /etc/tadoku/permissions
        - name: k8s-token
          mountPath: /var/run/secrets/tokens
          readOnly: true
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
      volumes:
        - name: tadoku-permissions
          configMap:
            name: tadoku-permissions
        - name: k8s-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: oathkeeper
---
apiVersion: v1
kind: Service
metadata:
  name: profile-api
  labels:
    app: profile-api
    service: profile-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: profile-api
