apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  name: tdk-dev-content-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: content-api
  namespace: tdk-dev-content-api
  labels:
    app: content-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      serviceAccountName: content-api
      containers:
      - name: content-api
        image: content-api-image
        resources:
          requests: {cpu: 25m, memory: 64Mi}
          limits: {cpu: "1", memory: 256Mi}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - {name: API_POSTGRES_HOST, value: tadoku-dev-db.tdk-dev-data.svc.cluster.local}
          - {name: API_POSTGRES_DATABASE, value: immersion}
          - {name: API_POSTGRES_SSLMODE, value: require}
          - name: API_POSTGRES_USER
            valueFrom: {secretKeyRef: {name: immersion.tadoku-dev-db.credentials.postgresql.acid.zalan.do, key: username}}
          - name: API_POSTGRES_PASSWORD
            valueFrom: {secretKeyRef: {name: immersion.tadoku-dev-db.credentials.postgresql.acid.zalan.do, key: password}}
          - name: API_PORT
            value: "8000"
          - name: API_JWKS
            value: "http://oathkeeper-api.tdk-dev-oathkeeper:4456/.well-known/jwks.json"
          - name: API_KETO_READ_URL
            value: "http://keto-read.tdk-dev-keto:4466"
        volumeMounts:
        - name: k8s-token
          mountPath: /var/run/secrets/tokens
          readOnly: true
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /livez
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
      volumes:
        - name: k8s-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: content-api
---
apiVersion: v1
kind: Service
metadata:
  name: content-api
  namespace: tdk-dev-content-api
  labels:
    app: content-api
    service: content-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: content-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: content-api
  namespace: tdk-dev-content-api
