load("./../../infra/dev/build/Tiltfile", "bazel_build")

watch_file("./deployments/api.yaml")
k8s_yaml(local("cat ./deployments/api.yaml"))

bazel_build(
  "authz-api-image",
  "//services/authz-api:load",
  deps=["./", "./../common/"],
)

k8s_resource("authz-api-source-schema", labels=["tools"], resource_deps=["tadoku-dev-db-credentials"])
k8s_resource("authz-api", labels=["backend"], resource_deps=["authz-api-source-schema", "kratos", "keto"])
