load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pages",
    srcs = [
        "page_create.go",
        "page_create_repository.go",
        "page_delete.go",
        "page_delete_repository.go",
        "page_find.go",
        "page_find_repository.go",
        "page_list.go",
        "page_list_repository.go",
        "page_update.go",
        "page_update_repository.go",
        "page_version_get.go",
        "page_version_get_repository.go",
        "page_version_list.go",
        "page_version_list_repository.go",
        "pages.go",
        "pages_repository.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/features/pages",
    visibility = [
        "//services/tadoku-api/app:__pkg__",
        "//services/tadoku-api/cmd/tadoku-api:__pkg__",
        "//services/tadoku-api/e2e:__pkg__",
    ],
    deps = [
        "//services/tadoku-api/generated/sqlc/pages",
        "//services/tadoku-api/infra/postgres",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/timex",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgerrcode//:pgerrcode",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgconn",
        "@com_github_jackc_pgx_v5//pgtype",
        "@com_github_jackc_pgx_v5//pgxpool",
    ],
)

go_test(
    name = "pages_test",
    srcs = [
        "page_create_repository_test.go",
        "page_create_test.go",
        "page_delete_repository_test.go",
        "page_update_repository_test.go",
        "page_version_get_repository_test.go",
        "page_version_list_repository_test.go",
        "pages_repository_test.go",
    ],
    args = ["-test.parallel=4"],
    env_inherit = ["TADOKU_TEST_POSTGRES_URL"],
    tags = [
        "no-cache",
        "no-remote-exec",
        "requires-network",
    ],
    deps = [
        ":pages",
        "//services/tadoku-api/infra/postgres",
        "//services/tadoku-api/internal/testpostgres",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgerrcode//:pgerrcode",
        "@com_github_jackc_pgx_v5//pgconn",
    ],
)
