// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: account_deletion.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const deleteProfileForAccountDeletion = `-- name: DeleteProfileForAccountDeletion :exec
delete from profiles
where user_id = $1
`

func (q *Queries) DeleteProfileForAccountDeletion(ctx context.Context, identityID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfileForAccountDeletion, identityID)
	return err
}

const listAccountDeletionSuppressedIdentityIDs = `-- name: ListAccountDeletionSuppressedIdentityIDs :many
select identity_id
from account_deletion_requests
where status in (
  'queued',
  'access_locked',
  'immersion_scrubbed',
  'caches_reconciled',
  'authorization_removed',
  'identity_deleted',
  'complete',
  'manual_attention'
)
order by identity_id
`

func (q *Queries) ListAccountDeletionSuppressedIdentityIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listAccountDeletionSuppressedIdentityIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var identity_id uuid.UUID
		if err := rows.Scan(&identity_id); err != nil {
			return nil, err
		}
		items = append(items, identity_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
