load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "timextest",
    testonly = True,
    srcs = ["timextest.go"],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/internal/timex/timextest",
    visibility = [
        "//services/tadoku-api/e2e:__pkg__",
        "//services/tadoku-api/internal/timex:__pkg__",
    ],
    deps = ["//services/tadoku-api/internal/timex/internal/clockstate"],
)
