load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "http",
    srcs = [
        "announcement_create.go",
        "announcement_delete.go",
        "announcement_update.go",
        "announcements.go",
        "authentication.go",
        "banned_users.go",
        "errors.go",
        "observability.go",
        "panic_recovery.go",
        "post_create.go",
        "post_delete.go",
        "post_find.go",
        "post_list.go",
        "proxy.go",
        "router.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/transport/http",
    visibility = ["//visibility:public"],
    deps = [
        "//services/tadoku-api/app",
        "//services/tadoku-api/generated/openapi",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/identity",
        "//services/tadoku-api/internal/permissions",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_github_google_uuid//:uuid",
        "@com_github_micahparks_keyfunc//:keyfunc",
        "@com_github_oapi_codegen_nullable//:nullable",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)

go_test(
    name = "http_test",
    srcs = [
        "authentication_test.go",
        "banned_users_test.go",
        "errors_test.go",
        "generated_test.go",
        "observability_test.go",
        "panic_recovery_test.go",
        "proxy_contract_test.go",
        "proxy_test.go",
    ],
    embed = [":http"],
    deps = [
        "//services/tadoku-api/app",
        "//services/tadoku-api/generated/openapi",
        "//services/tadoku-api/internal/errx",
        "//services/tadoku-api/internal/identity",
        "//services/tadoku-api/internal/permissions",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_github_google_uuid//:uuid",
        "@com_github_micahparks_keyfunc//:keyfunc",
        "@com_github_oapi_codegen_nullable//:nullable",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)
