load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "depolicy_lib",
    srcs = ["main.go"],
    importpath = "github.com/tadoku/tadoku/tools/ci/depolicy",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_satorunooshie_depolicy//:depolicy",
        "@org_golang_x_tools//go/analysis",
        "@org_golang_x_tools//go/analysis/passes/inspect",
        "@rules_go//go/runfiles",
    ],
)

go_binary(
    name = "depolicy",
    data = [
        "@tadoku_go_sdk//:ROOT",
        "@tadoku_go_sdk//:srcs",
    ],
    embed = [":depolicy_lib"],
    visibility = ["//visibility:public"],
    x_defs = {"sdkRootFile": "$(rlocationpath @tadoku_go_sdk//:ROOT)"},
)

go_test(
    name = "depolicy_test",
    srcs = ["main_test.go"],
    data = [
        "//:.depolicy.yaml",
        "@tadoku_go_sdk//:ROOT",
        "@tadoku_go_sdk//:srcs",
    ],
    embed = [":depolicy_lib"],
    x_defs = {"sdkRootFile": "$(rlocationpath @tadoku_go_sdk//:ROOT)"},
    deps = ["@rules_go//go/runfiles"],
)
