load('./../../infra/dev/build/Tiltfile', 'bazel_build')

k8s_yaml('./deployments/api.yaml')

bazel_build(
    'tadoku-api-image',
    '//services/tadoku-api:load',
    deps=['./', './../common/'],
)

k8s_resource(
    'tadoku-api',
    labels=['backend'],
    resource_deps=['tadoku-dev-db-credentials', 'oathkeeper', 'keto', 'authz-api', 'content-api', 'immersion-api', 'profile-api'],
)
