// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgxcompat

import (
	"context"
)

const getItem = `-- name: GetItem :one
select id, label from query_compat_items where id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int32) (QueryCompatItem, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i QueryCompatItem
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const insertItem = `-- name: InsertItem :exec
insert into query_compat_items (id, label) values ($1, $2)
`

type InsertItemParams struct {
	ID    int32
	Label string
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.Exec(ctx, insertItem, arg.ID, arg.Label)
	return err
}

const listItems = `-- name: ListItems :many
select id, label from query_compat_items order by id
`

func (q *Queries) ListItems(ctx context.Context) ([]QueryCompatItem, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryCompatItem{}
	for rows.Next() {
		var i QueryCompatItem
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameItem = `-- name: RenameItem :exec
update query_compat_items set label = $2 where id = $1
`

type RenameItemParams struct {
	ID    int32
	Label string
}

func (q *Queries) RenameItem(ctx context.Context, arg RenameItemParams) error {
	_, err := q.db.Exec(ctx, renameItem, arg.ID, arg.Label)
	return err
}
