kubeContext: homelab-dev
namespace: tdk-dev-routing
namespaces:
  - tdk-dev-routing
  - tdk-dev-data
  - tdk-dev-frontend-webv2
  - tdk-dev-oathkeeper
  - tdk-dev-tadoku-api
registry: registry.dev.lab/tadoku-dev-cli
ingressHost: tadoku.dev.lab
ingressClass: nginx
gatewayName: dev-cli-playground
gatewayNamespace: envoy-gateway-system
internalGateway: http://dev-cli-gateway.tdk-dev-routing.svc.cluster.local
ttl: 8h
bazelArgs:
  - --platforms=@rules_go//go/toolchain:linux_amd64
  - --@rules_go//go/config:pure
  - --jobs=2
dependencies:
  - name: database
    namespace: tdk-dev-data
    manifest: .dev/database.yaml
    retention: down
    readiness:
      - resource: job
        name: tadoku-${DEV_ROUTE}
        condition: Complete
        timeout: 300s
tasks:
  - name: migrate
    namespace: tdk-dev-tadoku-api
    manifest: .dev/migrate.yaml
    target: tadoku-dev-db.tdk-dev-data/tadoku-${DEV_ROUTE}
    dependencies:
      - database
    timeout: 5m
    imageName: migrate
    pushTarget: //services/tadoku-api/migrations:dev_push
    container: migrate
  - name: seed
    namespace: tdk-dev-tadoku-api
    manifest: .dev/seed.yaml
    target: tadoku-dev-db.tdk-dev-data/tadoku-${DEV_ROUTE}
    dependencies:
      - database
    timeout: 5m
    imageName: seed
    pushTarget: //.dev:seed_push
    container: seed
