apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 240
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: migrate
          image: invalid.example/replace-through-dev-task
          args:
            - -source
            - file:///migrations
            - up
          env:
            - name: POSTGRES_HOST
              value: tadoku-dev-db.default
            - name: POSTGRES_DATABASE
              value: immersion-${DEV_ROUTE}
            - name: POSTGRES_SSLMODE
              value: require
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immersion.tadoku-dev-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immersion.tadoku-dev-db.credentials.postgresql.acid.zalan.do
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 256Mi
