apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 240
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: seed
          image: invalid.example/replace-through-dev-task
          env:
            - name: PGHOST
              value: tadoku-dev-db.tdk-dev-data
            - name: PGDATABASE
              value: immersion-${DEV_ROUTE}
            - name: PGSSLMODE
              value: require
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: immersion.tadoku-dev-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: immersion.tadoku-dev-db.credentials.postgresql.acid.zalan.do
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 256Mi
