load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

filegroup(
    name = "up_files",
    srcs = glob(["*.up.sql"]),
    visibility = ["//services/tadoku-api/internal/testpostgres:__pkg__"],
)

pkg_tar(
    name = "tar",
    srcs = glob(["*.sql"]),
    mode = "0644",
    package_dir = "/migrations",
)

oci_image(
    name = "image",
    base = "@distroless_base_linux_amd64",
    entrypoint = ["/migrate"],
    tars = [
        "//services/common/migrate-runner:layer",
        ":tar",
    ],
    visibility = ["//visibility:public"],
)

oci_load(
    name = "load",
    image = ":image",
    repo_tags = [
        "ghcr.io/tadoku/tadoku/tadoku-api-migrations:latest",
        "bazel/services/tadoku-api/migrations:latest",
    ],
    visibility = ["//visibility:public"],
)

oci_push(
    name = "dev_push",
    image = ":image",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push",
    image = ":image",
    remote_tags = [
        "latest",
        "prod",
    ],
    repository = "ghcr.io/tadoku/tadoku/tadoku-api-migrations",
    visibility = ["//visibility:public"],
)
