load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "tadoku-api_lib",
    srcs = ["main.go"],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/cmd/tadoku-api",
    visibility = ["//visibility:private"],
    deps = [
        "//services/common/authz/roles",
        "//services/common/client/flipt",
        "//services/common/client/fliptmanagement",
        "//services/common/client/keto",
        "//services/common/client/kratos",
        "//services/common/client/s2s",
        "//services/common/domain",
        "//services/common/featureflags",
        "//services/common/postgresconfig",
        "//services/tadoku-api/app",
        "//services/tadoku-api/features/announcements",
        "//services/tadoku-api/features/audit",
        "//services/tadoku-api/features/authz",
        "//services/tadoku-api/features/contests",
        "//services/tadoku-api/features/featureaccess",
        "//services/tadoku-api/features/languages",
        "//services/tadoku-api/features/logs",
        "//services/tadoku-api/features/pages",
        "//services/tadoku-api/features/posts",
        "//services/tadoku-api/features/profile",
        "//services/tadoku-api/infra/postgres",
        "//services/tadoku-api/infra/valkey",
        "//services/tadoku-api/internal/permissions",
        "//services/tadoku-api/internal/timex",
        "//services/tadoku-api/transport/http",
        "@com_github_go_playground_validator_v10//:validator",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@com_github_kelseyhightower_envconfig//:envconfig",
        "@com_github_ory_kratos_client_go//:kratos-client-go",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/collectors",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@com_github_valkey_io_valkey_go//:valkey-go",
    ],
)

go_binary(
    name = "tadoku-api",
    embed = [":tadoku-api_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "tadoku-api_test",
    srcs = [
        "keto_test.go",
        "main_test.go",
    ],
    embed = [":tadoku-api_lib"],
    env_inherit = [
        "TADOKU_TEST_POSTGRES_URL",
        "TADOKU_TEST_VALKEY_URL",
    ],
    tags = [
        "no-cache",
        "no-remote-exec",
        "requires-network",
    ],
    deps = [
        "//services/common/client/keto",
        "//services/common/postgresconfig",
        "//services/tadoku-api/internal/testketo",
        "//services/tadoku-api/internal/testpostgres",
        "//services/tadoku-api/internal/testvalkey",
        "@com_github_valkey_io_valkey_go//:valkey-go",
    ],
)
