load("./../../infra/dev/build/Tiltfile", "bazel_build")
load("./../../k8s/dev/config/Tiltfile", "dev_registry_push_resource_deps")

watch_file('./deployments/api.yaml')
k8s_yaml(local('cat ./deployments/api.yaml'))

bazel_build(
  'token-reflector-image',
  '//services/token-reflector:load',
  deps=['./'],
)

k8s_resource('token-reflector', labels=["infra"], resource_deps=dev_registry_push_resource_deps())
