load('ext://helm_remote', 'helm_remote')

# mailhog
helm_remote('mailhog',
            repo_name='codecentric',
            repo_url='https://codecentric.github.io/helm-charts')
k8s_resource("mailhog", labels=["tools"])

# pgweb (postgres client)
k8s_yaml('./pgweb.yaml')
k8s_resource("pgweb", labels=["tools"])