// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/labstack/echo/v4"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for RoleUpdateRequestRole.
const (
	RoleUpdateRequestRoleBanned RoleUpdateRequestRole = "banned"
	RoleUpdateRequestRoleUser   RoleUpdateRequestRole = "user"
)

// Defines values for UserRoleRole.
const (
	UserRoleRoleAdmin  UserRoleRole = "admin"
	UserRoleRoleBanned UserRoleRole = "banned"
	UserRoleRoleGuest  UserRoleRole = "guest"
	UserRoleRoleUser   UserRoleRole = "user"
)

// PermissionCheckRequest defines model for PermissionCheckRequest.
type PermissionCheckRequest struct {
	Namespace string `json:"namespace"`
	Object    string `json:"object"`
	Relation  string `json:"relation"`
}

// PermissionCheckResponse defines model for PermissionCheckResponse.
type PermissionCheckResponse struct {
	Allowed bool `json:"allowed"`
}

// RoleUpdateRequest defines model for RoleUpdateRequest.
type RoleUpdateRequest struct {
	Reason string                `json:"reason"`
	Role   RoleUpdateRequestRole `json:"role"`
}

// RoleUpdateRequestRole defines model for RoleUpdateRequest.Role.
type RoleUpdateRequestRole string

// UserRole defines model for UserRole.
type UserRole struct {
	Role UserRoleRole `json:"role"`
}

// UserRoleRole defines model for UserRole.Role.
type UserRoleRole string

// PermissionCheckJSONRequestBody defines body for PermissionCheck for application/json ContentType.
type PermissionCheckJSONRequestBody = PermissionCheckRequest

// RoleUpdateJSONRequestBody defines body for RoleUpdate for application/json ContentType.
type RoleUpdateJSONRequestBody = RoleUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Fetches the role of the current user
	// (GET /current-user/role)
	RoleGet(ctx echo.Context) error
	// Checks if the current user has a specific permission
	// (POST /permission/check)
	PermissionCheck(ctx echo.Context) error
	// Checks if service is responsive
	// (GET /ping)
	Ping(ctx echo.Context) error
	// Update user role (admin only)
	// (PUT /users/{id}/role)
	RoleUpdate(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RoleGet converts echo context to params.
func (w *ServerInterfaceWrapper) RoleGet(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RoleGet(ctx)
	return err
}

// PermissionCheck converts echo context to params.
func (w *ServerInterfaceWrapper) PermissionCheck(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PermissionCheck(ctx)
	return err
}

// Ping converts echo context to params.
func (w *ServerInterfaceWrapper) Ping(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Ping(ctx)
	return err
}

// RoleUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) RoleUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RoleUpdate(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/current-user/role", wrapper.RoleGet)
	router.POST(baseURL+"/permission/check", wrapper.PermissionCheck)
	router.GET(baseURL+"/ping", wrapper.Ping)
	router.PUT(baseURL+"/users/:id/role", wrapper.RoleUpdate)

}
