load('ext://helm_resource', 'helm_resource', 'helm_repo')

helm_repo('bitnami', 'https://charts.bitnami.com/bitnami', resource_name='helm-repo-bitnami', labels=["infra"])

# kratos
k8s_yaml('./kratos/postgres.yaml')
helm_resource('postgres-kratos',
              'bitnami/postgresql',
              flags=[
                '-f', './kratos/postgres_values.yaml',
              ],
              deps=['./kratos/postgres_values.yaml'],
              resource_deps=['helm-repo-bitnami'])
k8s_resource("postgres-kratos", labels=["infra"])

# reading-contest
k8s_yaml('./reading-contest/postgres.yaml')
helm_resource('postgres-reading-contest',
              'bitnami/postgresql',
              flags=[
                '-f', './reading-contest/postgres_values.yaml',
              ],
              deps=['./reading-contest/postgres_values.yaml'],
              resource_deps=['helm-repo-bitnami'])
k8s_resource("postgres-reading-contest", labels=["infra"])

# blog
k8s_yaml('./blog/postgres.yaml')
helm_resource('postgres-blog',
              'bitnami/postgresql',
              flags=[
                '-f', './blog/postgres_values.yaml',
              ],
              deps=['./blog/postgres_values.yaml'],
              resource_deps=['helm-repo-bitnami'])
k8s_resource("postgres-blog", labels=["infra"])
