load('ext://helm_remote', 'helm_remote')

# Kratos
k8s_yaml('./kratos/postgres.yaml')
helm_remote('postgresql',
            repo_name='bitnami',
            repo_url='https://charts.bitnami.com/bitnami',
            values='./kratos/postgres_values.yaml')

# reading-contest
k8s_yaml('./reading-contest/postgres.yaml')
helm_remote('postgresql',
            repo_name='bitnami',
            repo_url='https://charts.bitnami.com/bitnami',
            values='./reading-contest/postgres_values.yaml')