k8s_yaml('deployments/web.yaml')

docker_build('frontends-web', '.',
  live_update=[
    # when package.json changes, we need to do a full build
    fall_back_on(['package.json', 'yarn.lock']),
    # Map the local source code into the container under /src
    sync('.', '/src'),
  ],
  dockerfile='Dockerfile.tilt')

k8s_resource('tadoku-web', port_forwards=3000)
