load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "errx",
    srcs = ["error.go"],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/internal/errx",
    visibility = ["//services/tadoku-api:__subpackages__"],
)

go_test(
    name = "errx_test",
    srcs = ["error_test.go"],
    deps = [":errx"],
)
