import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import authorizationApiSidebar from './docs/api/authorization/sidebar';
import contentApiSidebar from './docs/api/content/sidebar';
import immersionApiSidebar from './docs/api/immersion/sidebar';
import profileApiSidebar from './docs/api/profile/sidebar';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Develop',
      items: [
        'develop/toolchain',
        'develop/environment',
        'develop/verifying-changes',
        'develop/contributing',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'doc',
        id: 'architecture/index',
      },
      items: [
        'architecture/authorization',
        'architecture/service-tokens',
        'architecture/feature-flags',
        {
          type: 'category',
          label: 'Decisions',
          link: {
            type: 'doc',
            id: 'adr',
          },
          items: [{type: 'autogenerated', dirName: 'adr'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tadoku API',
      link: {
        type: 'doc',
        id: 'tadoku-api/index',
      },
      items: [
        'tadoku-api/conventions',
        'tadoku-api/contract',
        'tadoku-api/database',
        'tadoku-api/testing',
        'tadoku-api/http-e2e',
        'tadoku-api/user-journeys',
        'tadoku-api/import-boundaries',
        'tadoku-api/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      link: {
        type: 'doc',
        id: 'frontend/index',
      },
      items: [
        'frontend/webv2',
        'frontend/auth',
        'frontend/admin',
        'frontend/paper-styleguide',
        'frontend/paper-playground',
        'frontend/styleguide',
        'frontend/paper-composition',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {
        type: 'doc',
        id: 'operations/index',
      },
      items: [
        'operations/development-base',
        'operations/migration-recovery',
        'operations/account-deletion',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: [
        {
          type: 'category',
          label: 'Immersion API',
          link: {
            type: 'doc',
            id: 'api/immersion/immersion-api',
          },
          items: immersionApiSidebar.slice(1),
        },
        {
          type: 'category',
          label: 'Content API',
          link: {
            type: 'doc',
            id: 'api/content/content-api',
          },
          items: contentApiSidebar.slice(1),
        },
        {
          type: 'category',
          label: 'Profile API',
          link: {
            type: 'doc',
            id: 'api/profile/profile-api',
          },
          items: profileApiSidebar.slice(1),
        },
        {
          type: 'category',
          label: 'Authorization API',
          link: {
            type: 'doc',
            id: 'api/authorization/authz-api',
          },
          items: authorizationApiSidebar.slice(1),
        },
      ],
    },
  ],
};

export default sidebars;
