// Package internalapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package internalapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/labstack/echo/v4"
)

const (
	ServiceAuthScopes = "serviceAuth.Scopes"
)

// Defines values for AccountDeletionEligibilityConflictError.
const (
	RunningContestOwned AccountDeletionEligibilityConflictError = "running_contest_owned"
)

// AccountDeletionEligibilityConflict defines model for AccountDeletionEligibilityConflict.
type AccountDeletionEligibilityConflict struct {
	AvailableAfter time.Time                               `json:"available_after"`
	Error          AccountDeletionEligibilityConflictError `json:"error"`
}

// AccountDeletionEligibilityConflictError defines model for AccountDeletionEligibilityConflict.Error.
type AccountDeletionEligibilityConflictError string

// AccountDeletionEligibilityRequest defines model for AccountDeletionEligibilityRequest.
type AccountDeletionEligibilityRequest struct {
	UserId openapi_types.UUID `json:"user_id"`
}

// AccountDeletionLockRequest defines model for AccountDeletionLockRequest.
type AccountDeletionLockRequest struct {
	RequestId openapi_types.UUID `json:"request_id"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// AccountDeletionScrubRequest defines model for AccountDeletionScrubRequest.
type AccountDeletionScrubRequest struct {
	RequestId openapi_types.UUID `json:"request_id"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// InternalAccountDeletionEligibilityJSONRequestBody defines body for InternalAccountDeletionEligibility for application/json ContentType.
type InternalAccountDeletionEligibilityJSONRequestBody = AccountDeletionEligibilityRequest

// InternalAccountDeletionLockJSONRequestBody defines body for InternalAccountDeletionLock for application/json ContentType.
type InternalAccountDeletionLockJSONRequestBody = AccountDeletionLockRequest

// InternalAccountDeletionScrubJSONRequestBody defines body for InternalAccountDeletionScrub for application/json ContentType.
type InternalAccountDeletionScrubJSONRequestBody = AccountDeletionScrubRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// InternalAccountDeletionEligibility request with any body
	InternalAccountDeletionEligibilityWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InternalAccountDeletionEligibility(ctx context.Context, body InternalAccountDeletionEligibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InternalAccountDeletionLock request with any body
	InternalAccountDeletionLockWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InternalAccountDeletionLock(ctx context.Context, body InternalAccountDeletionLockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InternalAccountDeletionScrub request with any body
	InternalAccountDeletionScrubWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InternalAccountDeletionScrub(ctx context.Context, body InternalAccountDeletionScrubJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) InternalAccountDeletionEligibilityWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalAccountDeletionEligibilityRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalAccountDeletionEligibility(ctx context.Context, body InternalAccountDeletionEligibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalAccountDeletionEligibilityRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalAccountDeletionLockWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalAccountDeletionLockRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalAccountDeletionLock(ctx context.Context, body InternalAccountDeletionLockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalAccountDeletionLockRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalAccountDeletionScrubWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalAccountDeletionScrubRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InternalAccountDeletionScrub(ctx context.Context, body InternalAccountDeletionScrubJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInternalAccountDeletionScrubRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewInternalAccountDeletionEligibilityRequest calls the generic InternalAccountDeletionEligibility builder with application/json body
func NewInternalAccountDeletionEligibilityRequest(server string, body InternalAccountDeletionEligibilityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInternalAccountDeletionEligibilityRequestWithBody(server, "application/json", bodyReader)
}

// NewInternalAccountDeletionEligibilityRequestWithBody generates requests for InternalAccountDeletionEligibility with any type of body
func NewInternalAccountDeletionEligibilityRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/account-deletion-eligibility")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInternalAccountDeletionLockRequest calls the generic InternalAccountDeletionLock builder with application/json body
func NewInternalAccountDeletionLockRequest(server string, body InternalAccountDeletionLockJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInternalAccountDeletionLockRequestWithBody(server, "application/json", bodyReader)
}

// NewInternalAccountDeletionLockRequestWithBody generates requests for InternalAccountDeletionLock with any type of body
func NewInternalAccountDeletionLockRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/account-deletion-locks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInternalAccountDeletionScrubRequest calls the generic InternalAccountDeletionScrub builder with application/json body
func NewInternalAccountDeletionScrubRequest(server string, body InternalAccountDeletionScrubJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInternalAccountDeletionScrubRequestWithBody(server, "application/json", bodyReader)
}

// NewInternalAccountDeletionScrubRequestWithBody generates requests for InternalAccountDeletionScrub with any type of body
func NewInternalAccountDeletionScrubRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/account-deletion-scrubs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// InternalAccountDeletionEligibility request with any body
	InternalAccountDeletionEligibilityWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalAccountDeletionEligibilityResponse, error)

	InternalAccountDeletionEligibilityWithResponse(ctx context.Context, body InternalAccountDeletionEligibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalAccountDeletionEligibilityResponse, error)

	// InternalAccountDeletionLock request with any body
	InternalAccountDeletionLockWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalAccountDeletionLockResponse, error)

	InternalAccountDeletionLockWithResponse(ctx context.Context, body InternalAccountDeletionLockJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalAccountDeletionLockResponse, error)

	// InternalAccountDeletionScrub request with any body
	InternalAccountDeletionScrubWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalAccountDeletionScrubResponse, error)

	InternalAccountDeletionScrubWithResponse(ctx context.Context, body InternalAccountDeletionScrubJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalAccountDeletionScrubResponse, error)
}

type InternalAccountDeletionEligibilityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON409      *AccountDeletionEligibilityConflict
}

// Status returns HTTPResponse.Status
func (r InternalAccountDeletionEligibilityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InternalAccountDeletionEligibilityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InternalAccountDeletionLockResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r InternalAccountDeletionLockResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InternalAccountDeletionLockResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InternalAccountDeletionScrubResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r InternalAccountDeletionScrubResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InternalAccountDeletionScrubResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// InternalAccountDeletionEligibilityWithBodyWithResponse request with arbitrary body returning *InternalAccountDeletionEligibilityResponse
func (c *ClientWithResponses) InternalAccountDeletionEligibilityWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalAccountDeletionEligibilityResponse, error) {
	rsp, err := c.InternalAccountDeletionEligibilityWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalAccountDeletionEligibilityResponse(rsp)
}

func (c *ClientWithResponses) InternalAccountDeletionEligibilityWithResponse(ctx context.Context, body InternalAccountDeletionEligibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalAccountDeletionEligibilityResponse, error) {
	rsp, err := c.InternalAccountDeletionEligibility(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalAccountDeletionEligibilityResponse(rsp)
}

// InternalAccountDeletionLockWithBodyWithResponse request with arbitrary body returning *InternalAccountDeletionLockResponse
func (c *ClientWithResponses) InternalAccountDeletionLockWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalAccountDeletionLockResponse, error) {
	rsp, err := c.InternalAccountDeletionLockWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalAccountDeletionLockResponse(rsp)
}

func (c *ClientWithResponses) InternalAccountDeletionLockWithResponse(ctx context.Context, body InternalAccountDeletionLockJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalAccountDeletionLockResponse, error) {
	rsp, err := c.InternalAccountDeletionLock(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalAccountDeletionLockResponse(rsp)
}

// InternalAccountDeletionScrubWithBodyWithResponse request with arbitrary body returning *InternalAccountDeletionScrubResponse
func (c *ClientWithResponses) InternalAccountDeletionScrubWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InternalAccountDeletionScrubResponse, error) {
	rsp, err := c.InternalAccountDeletionScrubWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalAccountDeletionScrubResponse(rsp)
}

func (c *ClientWithResponses) InternalAccountDeletionScrubWithResponse(ctx context.Context, body InternalAccountDeletionScrubJSONRequestBody, reqEditors ...RequestEditorFn) (*InternalAccountDeletionScrubResponse, error) {
	rsp, err := c.InternalAccountDeletionScrub(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInternalAccountDeletionScrubResponse(rsp)
}

// ParseInternalAccountDeletionEligibilityResponse parses an HTTP response from a InternalAccountDeletionEligibilityWithResponse call
func ParseInternalAccountDeletionEligibilityResponse(rsp *http.Response) (*InternalAccountDeletionEligibilityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InternalAccountDeletionEligibilityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest AccountDeletionEligibilityConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseInternalAccountDeletionLockResponse parses an HTTP response from a InternalAccountDeletionLockWithResponse call
func ParseInternalAccountDeletionLockResponse(rsp *http.Response) (*InternalAccountDeletionLockResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InternalAccountDeletionLockResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseInternalAccountDeletionScrubResponse parses an HTTP response from a InternalAccountDeletionScrubWithResponse call
func ParseInternalAccountDeletionScrubResponse(rsp *http.Response) (*InternalAccountDeletionScrubResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InternalAccountDeletionScrubResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Checks whether an account owns a running contest that blocks deletion
	// (POST /internal/v1/account-deletion-eligibility)
	InternalAccountDeletionEligibility(ctx echo.Context) error
	// Idempotently prevents further mutations for an account
	// (POST /internal/v1/account-deletion-locks)
	InternalAccountDeletionLock(ctx echo.Context) error
	// Idempotently anonymizes and removes immersion data for a locked account
	// (POST /internal/v1/account-deletion-scrubs)
	InternalAccountDeletionScrub(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// InternalAccountDeletionEligibility converts echo context to params.
func (w *ServerInterfaceWrapper) InternalAccountDeletionEligibility(ctx echo.Context) error {
	var err error

	ctx.Set(ServiceAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalAccountDeletionEligibility(ctx)
	return err
}

// InternalAccountDeletionLock converts echo context to params.
func (w *ServerInterfaceWrapper) InternalAccountDeletionLock(ctx echo.Context) error {
	var err error

	ctx.Set(ServiceAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalAccountDeletionLock(ctx)
	return err
}

// InternalAccountDeletionScrub converts echo context to params.
func (w *ServerInterfaceWrapper) InternalAccountDeletionScrub(ctx echo.Context) error {
	var err error

	ctx.Set(ServiceAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalAccountDeletionScrub(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/internal/v1/account-deletion-eligibility", wrapper.InternalAccountDeletionEligibility)
	router.POST(baseURL+"/internal/v1/account-deletion-locks", wrapper.InternalAccountDeletionLock)
	router.POST(baseURL+"/internal/v1/account-deletion-scrubs", wrapper.InternalAccountDeletionScrub)

}
