load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "app",
    srcs = ["app.go"],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/app",
    visibility = [
        "//services/tadoku-api/cmd/tadoku-api:__pkg__",
        "//services/tadoku-api/e2e:__pkg__",
        "//services/tadoku-api/transport/http:__pkg__",
    ],
    deps = [
        "//services/tadoku-api/features/access",
        "//services/tadoku-api/features/content",
    ],
)
