load("./../../infra/dev/build/Tiltfile", "bazel_build")

# Api container
watch_file('./deployments/api.yaml')
k8s_yaml(local('cat ./deployments/api.yaml'))

bazel_build(
  'immersion-api-image',
  '//services/immersion-api:load',
  deps=['./', './../common/'],
)

bazel_build(
  'tadoku-api-migrations-image',
  '//services/tadoku-api/migrations:load',
  deps=[
    './../common/migrate-runner/',
    './storage/postgres/migrations/',
    './../tadoku-api/migrations/',
  ],
)

k8s_resource(
  'immersion-api',
  labels=["backend"],
  resource_deps=[
    "tadoku-dev-db-credentials",
    "flipt",
    "kratos",
    "keto",
    "oathkeeper",
    "valkey-immersion",
  ],
)
