# Api container
watch_file('./deployments/api.yaml')
k8s_yaml(local('bazel run //services/immersion-api/deployments:api'))

custom_build(
  ref='immersion-api-migrate-image',
  command=(
    'bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 {image_target} -- --norun && ' +
    'docker tag {bazel_image} $EXPECTED_REF').format(
      image_target='//services/immersion-api/storage/postgres/migrations:image',
      bazel_image='bazel/services/immersion-api/storage/postgres/migrations:image'
    ),
  deps=['./storage/postgres/migrations/'],
)

custom_build(
  ref='immersion-api-image',
  command=(
    'bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 {image_target} -- --norun && ' +
    'docker tag {bazel_image} $EXPECTED_REF').format(
      image_target='//services/immersion-api:image',
      bazel_image='bazel/services/immersion-api:image'
    ),
  deps=['./', './../common/', './../../dev/permissions/'],
)

k8s_resource('immersion-api', labels=["backend"])
