load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "e2e_test",
    size = "medium",
    srcs = [
        "access_level_test.go",
        "announcement_create_test.go",
        "announcement_delete_test.go",
        "announcement_update_test.go",
        "announcements_test.go",
        "api_test.go",
        "authentication_test.go",
        "banned_users_test.go",
        "dependency_failure_test.go",
        "golden_test.go",
        "journey_test.go",
        "legacy_content_test.go",
        "page_create_test.go",
        "page_delete_test.go",
        "page_find_test.go",
        "page_list_test.go",
        "page_update_test.go",
        "post_create_test.go",
        "post_delete_test.go",
        "post_find_test.go",
        "post_list_test.go",
        "post_update_test.go",
        "post_version_get_test.go",
        "post_version_list_test.go",
        "routing_test.go",
    ],
    data = glob([
        "testdata/**/*.http",
        "testdata/**/*.json",
        "testdata/**/*.sql",
    ]) + ["//services/tadoku-api/spec:openapi.yaml"],
    env_inherit = [
        "CI",
        "TADOKU_GOLDEN_SOURCE_ROOT",
        "TADOKU_TEST_POSTGRES_URL",
    ],
    tags = [
        "no-cache",
        "no-remote-exec",
        "requires-network",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    deps = [
        "//services/common/authz/roles",
        "//services/common/client/keto",
        "//services/common/domain",
        "//services/common/middleware",
        "//services/content-api/domain",
        "//services/content-api/http/rest",
        "//services/content-api/http/rest/openapi",
        "//services/content-api/storage/postgres",
        "//services/tadoku-api/app",
        "//services/tadoku-api/features/announcements",
        "//services/tadoku-api/features/pages",
        "//services/tadoku-api/features/posts",
        "//services/tadoku-api/generated/openapi",
        "//services/tadoku-api/internal/identity",
        "//services/tadoku-api/internal/permissions",
        "//services/tadoku-api/internal/testketo",
        "//services/tadoku-api/internal/testpostgres",
        "//services/tadoku-api/internal/timex",
        "//services/tadoku-api/transport/http",
        "@com_github_getkin_kin_openapi//openapi3",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_github_jackc_pgx_v4//:pgx",
        "@com_github_jackc_pgx_v4//stdlib",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@com_github_labstack_echo_v4//:echo",
        "@com_github_prometheus_client_golang//prometheus",
        "@rules_go//go/tools/bazel",
    ],
)
