load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "e2e_test",
    size = "medium",
    srcs = [
        "access_level_test.go",
        "announcement_create_test.go",
        "announcement_delete_test.go",
        "announcement_update_test.go",
        "announcements_test.go",
        "api_test.go",
        "authentication_test.go",
        "banned_users_test.go",
        "dependency_failure_test.go",
        "golden_test.go",
        "legacy_content_test.go",
        "routing_test.go",
    ],
    data = glob([
        "testdata/**/*.http",
        "testdata/**/*.json",
        "testdata/**/*.sql",
    ]),
    env_inherit = ["TADOKU_TEST_POSTGRES_URL"],
    tags = [
        "no-cache",
        "no-remote-exec",
        "requires-network",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    deps = [
        "//services/common/authz/roles",
        "//services/common/client/keto",
        "//services/common/domain",
        "//services/common/middleware",
        "//services/content-api/domain",
        "//services/content-api/http/rest",
        "//services/content-api/http/rest/openapi",
        "//services/content-api/storage/postgres",
        "//services/tadoku-api/app",
        "//services/tadoku-api/features/content",
        "//services/tadoku-api/generated/openapi",
        "//services/tadoku-api/internal/identity",
        "//services/tadoku-api/internal/permissions",
        "//services/tadoku-api/internal/testketo",
        "//services/tadoku-api/internal/testpostgres",
        "//services/tadoku-api/internal/timex",
        "//services/tadoku-api/transport/http",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_github_jackc_pgx_v4//:pgx",
        "@com_github_jackc_pgx_v4//stdlib",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@com_github_labstack_echo_v4//:echo",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)
