load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "scoring",
    srcs = [
        "domain.go",
        "scoring_repository.go",
        "scoring_service.go",
    ],
    importpath = "github.com/tadoku/tadoku/services/tadoku-api/features/scoring",
    visibility = ["//visibility:public"],
    deps = [
        "//services/tadoku-api/domain/activities",
        "//services/tadoku-api/generated/sqlc/scoring",
        "//services/tadoku-api/infra/postgres",
        "//services/tadoku-api/internal/errx",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgtype",
        "@com_github_jackc_pgx_v5//pgxpool",
    ],
)
