name: build-frontend-auth
on:
  schedule:
    # monthly at 10th of every month
    - cron: "0 0 10 * *"

  push:
    paths:
      - "frontend/apps/auth/**"
      - "frontend/packages/ui/**"
      - ".github/workflows/build-frontend-auth.yaml"
      - "frontend/pnpm-lock.yaml"
      - "frontend/Dockerfile"
      - "frontend/.npmrc"
jobs:
  build:
    name: Build auth
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10.10.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm --filter auth run build

  publish:
    name: Publish Image
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build \
            --build-arg PROJECT_NAME=auth \
            -t ghcr.io/tadoku/tadoku/frontend-auth:latest \
            .

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@81e514348e19b6112ce2a7e3ecbafe19c1e1f567 # v0.3.1
        with:
          version: v0.72.0

      - name: Scan image
        run: |
          trivy image \
            --exit-code 1 \
            --ignore-unfixed \
            --scanners vuln \
            --severity CRITICAL,HIGH \
            ghcr.io/tadoku/tadoku/frontend-auth:latest

      - name: Push images
        env:
          IMAGE_NAME: ghcr.io/tadoku/tadoku/frontend-auth
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" |
            docker login ghcr.io -u tadoku --password-stdin
          docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${GITHUB_SHA}"
          docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:prod"
          docker push "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:${GITHUB_SHA}"
          docker push "${IMAGE_NAME}:prod"
