apiVersion: v1
kind: Namespace
metadata:
  name: tdk-immersion-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immersion-api
  namespace: tdk-immersion-api
  labels:
    app: immersion-api
spec:
  selector:
    matchLabels:
      app: immersion-api
  template:
    metadata:
      labels:
        app: immersion-api
    spec:
      serviceAccountName: immersion-api
      initContainers:
        - name: migrations
          image: immersion-api-migrate-image
          command: ['/migrate']
          args: ['-source', 'file:///migrations', '-database', '$(DATABASE_URL)', 'up']
          env:
          - name: DATABASE_URL
            value: "postgres://immersion:foobar@postgres-immersion.default/immersion?sslmode=disable"
      containers:
      - name: immersion-api
        image: immersion-api-image
        ports:
        - containerPort: 8000
        env:
          - name: API_POSTGRES_URL
            value: "postgres://immersion:foobar@postgres-immersion.default/immersion?sslmode=disable"
          - name: API_PORT
            value: "8000"
          - name: API_JWKS
            value: "http://oathkeeper-api.default:4456/.well-known/jwks.json"
          - name: API_KRATOS_URL
            value: "http://kratos-admin.default"
          - name: API_OATHKEEPER_URL
            value: "http://oathkeeper-proxy.default:4455"
          - name: API_KETO_READ_URL
            value: "http://keto-read.default:4466"
          - name: API_KETO_WRITE_URL
            value: "http://keto-write.default:4467"
          - name: API_VALKEY_URL
            value: "redis://valkey-immersion.default:6379"
          - name: SERVICE_NAME
            value: "immersion-api"
        volumeMounts:
        - name: k8s-token
          mountPath: /var/run/secrets/tokens
          readOnly: true
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /livez
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
      volumes:
        - name: k8s-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: immersion-api
---
apiVersion: v1
kind: Service
metadata:
  name: immersion-api
  namespace: tdk-immersion-api
  labels:
    app: immersion-api
    service: immersion-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: immersion-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: immersion-api
  namespace: tdk-immersion-api
